--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-20-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body FIDE_SALUDTOTAL_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "FIDE_SALUDTOTAL_BD"."FIDE_SALUDTOTAL_PKG" AS 


------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_INSERT_SP(
P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_NOMBRE_ALERGIA IN FIDE_ALERGIA_TB.NOMBRE_ALERGIA%TYPE
)IS
BEGIN
    INSERT INTO FIDE_ALERGIA_TB(ID_ALERGIA,NOMBRE_ALERGIA)
    VALUES (P_ID_ALERGIA,P_NOMBRE_ALERGIA);
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
-------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CITA_DELETE_SP(
P_ID_CITA IN FIDE_CITA_TB.ID_CITA%TYPE,
P_ID_PACIENTE IN FIDE_CITA_TB.ID_PACIENTE%TYPE,
P_ID_MEDICO IN FIDE_CITA_TB.ID_MEDICO%TYPE,
P_ID_SUCURSAL IN FIDE_CITA_TB.ID_SUCURSAL%TYPE,
P_FECHA_HORA_CITA IN FIDE_CITA_TB.FECHA_HORA_CITA%TYPE,
P_MOTIVA_CONSULTA IN FIDE_CITA_TB.MOTIVA_CONSULTA%TYPE,
P_ID_ESTADO IN FIDE_CITA_TB.ID_ESTADO%TYPE
)IS 
BEGIN
    UPDATE FIDE_CITA_TB
    SET 
        ID_PACIENTE = P_ID_PACIENTE,
        ID_MEDICO = P_ID_MEDICO,
        ID_SUCURSAL = P_ID_SUCURSAL,
        FECHA_HORA_CITA = P_FECHA_HORA_CITA,
        MOTIVA_CONSULTA = P_MOTIVA_CONSULTA,
        ID_ESTADO = P_ID_ESTADO
    WHERE P_ID_CITA = ID_CITA;
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
-------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CITA_INSERT_SP(
P_ID_CITA IN FIDE_CITA_TB.ID_CITA%TYPE,
P_ID_PACIENTE IN FIDE_CITA_TB.ID_PACIENTE%TYPE,
P_ID_MEDICO IN FIDE_CITA_TB.ID_MEDICO%TYPE,
P_ID_SUCURSAL IN FIDE_CITA_TB.ID_SUCURSAL%TYPE,
P_FECHA_HORA_CITA IN FIDE_CITA_TB.FECHA_HORA_CITA%TYPE,
P_MOTIVA_CONSULTA IN FIDE_CITA_TB.MOTIVA_CONSULTA%TYPE,
P_ID_ESTADO IN FIDE_CITA_TB.ID_ESTADO%TYPE
)IS
BEGIN
    INSERT INTO FIDE_CITA_TB(ID_CITA,ID_PACIENTE,ID_MEDICO,ID_SUCURSAL,FECHA_HORA_CITA,MOTIVA_CONSULTA,ID_ESTADO)
    VALUES (P_ID_CITA,P_ID_PACIENTE,P_ID_MEDICO,P_ID_SUCURSAL,P_FECHA_HORA_CITA,P_MOTIVA_CONSULTA,P_ID_ESTADO);
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
----------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ENFERMEDAD_CRONICA_INSERT_SP(
P_ID_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.ID_ENFERMEDAD%TYPE,
P_NOMBRE_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.NOMBRE_ENFERMEDAD%TYPE
)IS
BEGIN
    INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB(ID_ENFERMEDAD,NOMBRE_ENFERMEDAD)
    VALUES (P_ID_ENFERMEDAD,P_NOMBRE_ENFERMEDAD);
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_HISTORIAL_CLINICO_INSERT_SP(
P_ID_HISTORIAL IN FIDE_HISTORIAL_CLINICO_TB.ID_HISTORIAL%TYPE,
P_ID_CITA IN FIDE_HISTORIAL_CLINICO_TB.ID_CITA%TYPE,
P_DIAGNOSTICO IN FIDE_HISTORIAL_CLINICO_TB.DIAGNOSTICO%TYPE,
P_PROCEDIMIENTOS_REALIZADOS IN FIDE_HISTORIAL_CLINICO_TB.PROCEDIMIENTOS_REALIZADOS%TYPE,
P_TRATAMIENTO_SUGERIDO IN FIDE_HISTORIAL_CLINICO_TB.TRATAMIENTO_SUGERIDO%TYPE
)IS 
BEGIN
    INSERT INTO FIDE_HISTORIAL_CLINICO_TB(ID_HISTORIAL,ID_CITA,DIAGNOSTICO,PROCEDIMIENTOS_REALIZADOS,TRATAMIENTO_SUGERIDO)
    VALUES(P_ID_HISTORIAL,P_ID_CITA,P_DIAGNOSTICO,P_PROCEDIMIENTOS_REALIZADOS,P_TRATAMIENTO_SUGERIDO);
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
-----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ALERGIA_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ALERGIA_TB.ID_PACIENTE%TYPE,
P_ID_ALERGIA IN FIDE_PACIENTE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ALERGIA_TB.FECHA_DIAGNOSTICO%TYPE,
P_NIVEL_SEVERIDAD IN FIDE_PACIENTE_ALERGIA_TB.NIVEL_SEVERIDAD%TYPE,
P_NOTAS IN FIDE_PACIENTE_ALERGIA_TB.NOTAS%TYPE
) IS 
BEGIN
    INSERT INTO FIDE_PACIENTE_ALERGIA_TB(ID_PACIENTE,ID_ALERGIA,FECHA_DIAGNOSTICO,NIVEL_SEVERIDAD,NOTAS)
    VALUES (P_ID_PACIENTE,P_ID_ALERGIA,P_FECHA_DIAGNOSTICO,P_NIVEL_SEVERIDAD,P_NOTAS);
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
-----------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_DELETE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE
) IS
BEGIN
    UPDATE FIDE_PACIENTE_TB
    SET ID_ESTADO = 2
    WHERE ID_PACIENTE = P_ID_PACIENTE;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ENFERMEDAD_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_PACIENTE%TYPE,
P_ID_ENFERMEDAD IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_ENFERMEDAD%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ENFERMEDAD_TB.FECHA_DIAGNOSTICO%TYPE,
P_NOTAS IN FIDE_PACIENTE_ENFERMEDAD_TB.NOTAS%TYPE
)IS
BEGIN
    INSERT INTO FIDE_PACIENTE_ENFERMEDAD_TB(ID_PACIENTE,ID_ENFERMEDAD,FECHA_DIAGNOSTICO,NOTAS)
    VALUES (P_ID_PACIENTE,P_ID_ENFERMEDAD,P_FECHA_DIAGNOSTICO,P_NOTAS);
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
---------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE,
P_NOMBRE IN FIDE_PACIENTE_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PACIENTE_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PACIENTE_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_NACIMIENTO IN FIDE_PACIENTE_TB.FECHA_NACIMIENTO%TYPE,
P_ID_DIRECCION IN FIDE_PACIENTE_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN FIDE_PACIENTE_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO FIDE_PACIENTE_TB(ID_PACIENTE,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO,ID_DIRECCION,ID_ESTADO)
    VALUES (P_ID_PACIENTE,P_NOMBRE,P_APELLIDO_PATERNO,P_APELLIDO_MATERNO,P_FECHA_NACIMIENTO,P_ID_DIRECCION,P_ID_ESTADO);
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE,
P_NOMBRE IN FIDE_PACIENTE_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PACIENTE_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PACIENTE_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_NACIMIENTO IN FIDE_PACIENTE_TB.FECHA_NACIMIENTO%TYPE,
P_ID_DIRECCION IN FIDE_PACIENTE_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN FIDE_PACIENTE_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_PACIENTE_TB
    SET NOMBRE = P_NOMBRE,
        APELLIDO_PATERNO = P_APELLIDO_PATERNO,
        APELLIDO_MATERNO = P_APELLIDO_MATERNO,
        FECHA_NACIMIENTO = P_FECHA_NACIMIENTO,
        ID_DIRECCION = P_ID_DIRECCION,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_PACIENTE = P_ID_PACIENTE;
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
-----------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CITA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_CITA_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;
---------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ENFERMEDAD_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PACIENTE_ENFERMEDAD_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;
------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PACIENTE_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;

-----------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ALERGIA_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ALERGIA_TB.ID_PACIENTE%TYPE,
P_ID_ALERGIA IN FIDE_PACIENTE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ALERGIA_TB.FECHA_DIAGNOSTICO%TYPE,
P_NIVEL_SEVERIDAD IN FIDE_PACIENTE_ALERGIA_TB.NIVEL_SEVERIDAD%TYPE,
P_NOTAS IN FIDE_PACIENTE_ALERGIA_TB.NOTAS%TYPE
)IS
BEGIN
    UPDATE FIDE_PACIENTE_ALERGIA_TB
    SET 
        ID_PACIENTE = P_ID_PACIENTE,
        ID_ALERGIA = P_ID_ALERGIA,
        FECHA_DIAGNOSTICO = P_FECHA_DIAGNOSTICO,
        NIVEL_SEVERIDAD = P_NIVEL_SEVERIDAD,
        NOTAS = P_NOTAS
    WHERE P_ID_PACIENTE = ID_PACIENTE;
    COMMIT;
END;
----------------------------------------------------------------------------------------------------
PROCEDURE FIDE_HISTORIAL_CLINICO_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_HISTORIAL_CLINICO_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;
-------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_HISTORIAL_CLINICO_UPDATE_SP(
P_ID_HISTORIAL IN FIDE_HISTORIAL_CLINICO_TB.ID_HISTORIAL%TYPE,
P_ID_CITA IN FIDE_HISTORIAL_CLINICO_TB.ID_CITA%TYPE,
P_DIAGNOSTICO IN FIDE_HISTORIAL_CLINICO_TB.DIAGNOSTICO%TYPE,
P_PROCEDIMIENTOS_REALIZADOS IN FIDE_HISTORIAL_CLINICO_TB.PROCEDIMIENTOS_REALIZADOS%TYPE,
P_TRATAMIENTO_SUGERIDO IN FIDE_HISTORIAL_CLINICO_TB.TRATAMIENTO_SUGERIDO%TYPE
)IS
BEGIN
    UPDATE FIDE_HISTORIAL_CLINICO_TB
    SET ID_HISTORIAL = P_ID_HISTORIAL,
        ID_CITA = P_ID_CITA,
        DIAGNOSTICO = P_DIAGNOSTICO,
        PROCEDIMIENTOS_REALIZADOS = P_PROCEDIMIENTOS_REALIZADOS,
        TRATAMIENTO_SUGERIDO = P_TRATAMIENTO_SUGERIDO
    WHERE P_ID_HISTORIAL = ID_HISTORIAL;
END;
-----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ALERGIA_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;
----------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ENFERMEDAD_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_PACIENTE%TYPE,
P_ID_ENFERMEDAD IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_ENFERMEDAD%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ENFERMEDAD_TB.FECHA_DIAGNOSTICO%TYPE,
P_NOTAS IN FIDE_PACIENTE_ENFERMEDAD_TB.NOTAS%TYPE
)IS 
BEGIN
    UPDATE FIDE_PACIENTE_ENFERMEDAD_TB
    SET 
        ID_PACIENTE = P_ID_PACIENTE,
        ID_ENFERMEDAD = P_ID_ENFERMEDAD,
        FECHA_DIAGNOSTICO = P_FECHA_DIAGNOSTICO,
        NOTAS = P_NOTAS
    WHERE P_ID_PACIENTE = ID_PACIENTE;
    COMMIT;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
-----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_UPDATE_SP(
P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_NOMBRE_ALERGIA IN FIDE_ALERGIA_TB.NOMBRE_ALERGIA%TYPE
)IS
BEGIN
    UPDATE FIDE_ALERGIA_TB
    SET ID_ALERGIA =P_ID_ALERGIA,
        NOMBRE_ALERGIA = P_NOMBRE_ALERGIA
    WHERE P_ID_ALERGIA = ID_ALERGIA;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ENFERMEDAD_CRONICA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ENFERMEDAD_CRONICA_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;
------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_UPDATE_SP(
P_ID_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.ID_ENFERMEDAD%TYPE,
P_NOMBRE_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.NOMBRE_ENFERMEDAD%TYPE
)IS
BEGIN
    UPDATE FIDE_ENFERMEDAD_CRONICA_TB
    SET ID_ENFERMEDAD =P_ID_ENFERMEDAD,
        NOMBRE_ENFERMEDAD = P_NOMBRE_ENFERMEDAD
    WHERE P_ID_ENFERMEDAD = ID_ENFERMEDAD;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;
-------------------------------------------------------------------------------------------------------------
--1. PROCEDIMIENTOS SUCURSLA
PROCEDURE FIDE_SUCURSAL_TB_INSERTAR_SP(
P_NOMBRE IN FIDE_SUCURSAL_TB.NOMBRE%TYPE,
P_ID_DIRECCION IN FIDE_SUCURSAL_TB.ID_DIRECCION%TYPE,
P_TELEFONO IN FIDE_SUCURSAL_TB.TELEFONO%TYPE,
P_ID_ESTADO IN FIDE_SUCURSAL_TB.ID_ESTADO%TYPE
)IS
    V_NUEVO_ID NUMBER; -- Variable temporal para guardar el ID
BEGIN
    
    SELECT NVL(MAX(ID_SUCURSAL), 0) + 1 INTO V_NUEVO_ID FROM FIDE_SUCURSAL_TB;

    INSERT INTO FIDE_SUCURSAL_TB(ID_SUCURSAL, NOMBRE, ID_DIRECCION, TELEFONO, ID_ESTADO)
    VALUES(V_NUEVO_ID, P_NOMBRE, P_ID_DIRECCION, P_TELEFONO, P_ID_ESTADO);
        
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Sucursal insertada con ID: ' || V_NUEVO_ID);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado al insertar sucursal: ' || SQLERRM);
END FIDE_SUCURSAL_TB_INSERTAR_SP;

PROCEDURE FIDE_SUCURSAL_TB_ACTUALIZAR_SP(
P_ID_SUCURSAL IN FIDE_SUCURSAL_TB.ID_SUCURSAL%TYPE,
P_NOMBRE IN FIDE_SUCURSAL_TB.NOMBRE%TYPE,
P_ID_DIRECCION IN FIDE_SUCURSAL_TB.ID_DIRECCION%TYPE,
P_TELEFONO IN FIDE_SUCURSAL_TB.TELEFONO%TYPE
)IS
BEGIN
    UPDATE FIDE_SUCURSAL_TB
    SET NOMBRE = P_NOMBRE, TELEFONO = P_TELEFONO, ID_DIRECCION = P_ID_DIRECCION
    WHERE ID_SUCURSAL = P_ID_SUCURSAL;
        
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro la SUCURSAL con ID: ' || P_ID_SUCURSAL);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Sucursal actualizada correctamente.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al actualizar la sucursal: ' || SQLERRM);
END FIDE_SUCURSAL_TB_ACTUALIZAR_SP;
-----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SUCURSAL_TB_ELIMINAR_SP(
P_ID_SUCURSAL IN FIDE_SUCURSAL_TB.ID_SUCURSAL%TYPE,
P_ID_ESTADO IN FIDE_SUCURSAL_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_SUCURSAL_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_SUCURSAL = P_ID_SUCURSAL;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro la SUCURSAL con ID: ' || P_ID_SUCURSAL);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Estado de la SUCURSAL actualizado correctamente.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al cambiar estado de sucursal: ' || SQLERRM);
END FIDE_SUCURSAL_TB_ELIMINAR_SP;
----------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SUCURSAL_TB_LISTAR_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_SUCURSAL_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END FIDE_SUCURSAL_TB_LISTAR_SP;
-----------------------------------------------------------------------------------------------------------------
    --2. PROCEDIMIENTOS PERSONAL
PROCEDURE FIDE_PERSONAL_TB_INSERTAR_SP(
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_NOMBRE IN FIDE_PERSONAL_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PERSONAL_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PERSONAL_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_CONTRATACION IN FIDE_PERSONAL_TB.FECHA_CONTRATACION%TYPE,
P_ID_SUCURSAL IN FIDE_PERSONAL_TB.ID_SUCURSAL%TYPE,
P_ID_ROL_PERSONAL IN FIDE_PERSONAL_TB.ID_ROL_PERSONAL%TYPE,
P_ID_ESTADO IN FIDE_PERSONAL_TB.ID_ESTADO%TYPE
)IS
BEGIN
    INSERT INTO FIDE_PERSONAL_TB(ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO)
    VALUES(P_ID_PERSONAL, P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_FECHA_CONTRATACION, P_ID_SUCURSAL, P_ID_ROL_PERSONAL, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Personal insertado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error insertando personal: ' || SQLERRM);
END FIDE_PERSONAL_TB_INSERTAR_SP;
---------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PERSONAL_TB_ACTUALIZAR_SP(
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_NOMBRE IN FIDE_PERSONAL_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PERSONAL_TB.APELLIDO_PATERNO%TYPE,
P_ID_SUCURSAL IN FIDE_PERSONAL_TB.ID_SUCURSAL%TYPE,
P_ID_ROL_PERSONAL IN FIDE_PERSONAL_TB.ID_ROL_PERSONAL%TYPE
)IS
BEGIN
    UPDATE FIDE_PERSONAL_TB
    SET NOMBRE = P_NOMBRE, 
        APELLIDO_PATERNO = P_APELLIDO_PATERNO,
        ID_SUCURSAL = P_ID_SUCURSAL,
        ID_ROL_PERSONAL = P_ID_ROL_PERSONAL
    WHERE ID_PERSONAL = P_ID_PERSONAL;
        
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro PERSONAL con ID: '||P_ID_PERSONAL);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Datos de PERSONAL actualizados.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error actualizando personal: ' || SQLERRM);
END FIDE_PERSONAL_TB_ACTUALIZAR_SP;
----------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PERSONAL_TB_ELIMINAR_SP(
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_ID_ESTADO IN FIDE_PERSONAL_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_PERSONAL_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_PERSONAL = P_ID_PERSONAL;
        
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro PERSONAL con ID: '||P_ID_PERSONAL);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Estado del PERSONAL actualizado.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error soft-delete personal: ' || SQLERRM);
END FIDE_PERSONAL_TB_ELIMINAR_SP;
--------------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PERSONAL_TB_LISTAR_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PERSONAL_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar personal: ' || SQLERRM);
END FIDE_PERSONAL_TB_LISTAR_SP;
---------------------------------------------------------------------------------------------------------------------
    --PROCEDIMIENTOS USUARIO
PROCEDURE FIDE_USUARIO_TB_INSERTAR_SP(
P_NOMBRE_USUARIO IN FIDE_USUARIO_TB.NOMBRE_USUARIO%TYPE,
P_CONTRASENNA IN FIDE_USUARIO_TB.CONTRASENNA%TYPE,
P_ID_PERSONAL IN FIDE_USUARIO_TB.ID_PERSONAL%TYPE,
P_ID_PACIENTE IN FIDE_USUARIO_TB.ID_PACIENTE%TYPE,
P_ID_ROL_SISTEMA IN FIDE_USUARIO_TB.ID_ROL_SISTEMA%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
)IS
    V_NUEVO_ID NUMBER;
BEGIN
    --Calcular siguiente ID
    SELECT NVL(MAX(ID_USUARIO), 0) + 1 INTO V_NUEVO_ID FROM FIDE_USUARIO_TB;

    INSERT INTO FIDE_USUARIO_TB(ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
    VALUES(V_NUEVO_ID, P_NOMBRE_USUARIO, P_CONTRASENNA, P_ID_PERSONAL, P_ID_PACIENTE, P_ID_ROL_SISTEMA, P_ID_ESTADO);
        
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Usuario creado con ID: ' || V_NUEVO_ID);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creando usuario: ' || SQLERRM);
END FIDE_USUARIO_TB_INSERTAR_SP;
-------------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIO_TB_ACTUALIZAR_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_ID_ROL_SISTEMA IN FIDE_USUARIO_TB.ID_ROL_SISTEMA%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET ID_ROL_SISTEMA = P_ID_ROL_SISTEMA,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_USUARIO = P_ID_USUARIO;
        
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Usuario no encontrado.');
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Datos de usuario actualizados.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error actualizando usuario: ' || SQLERRM);
END FIDE_USUARIO_TB_ACTUALIZAR_SP;
----------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIO_TB_CAMBIAR_CLAVE_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NUEVA_CONTRASENNA IN FIDE_USUARIO_TB.CONTRASENNA%TYPE
)IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET CONTRASENNA = P_NUEVA_CONTRASENNA
    WHERE ID_USUARIO = P_ID_USUARIO;
        
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Usuario no encontrado.');
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Clave actualizada.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error actualizando clave: ' || SQLERRM);
END FIDE_USUARIO_TB_CAMBIAR_CLAVE_SP;
----------------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIO_TB_LISTAR_SP(
    P_CURSOR OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_USUARIO_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar usuarios: ' || SQLERRM);
END FIDE_USUARIO_TB_LISTAR_SP;

-------------------------------------------------------------------------------------------------------------------
--PROCEDIMIENTOS FACTURA
PROCEDURE FIDE_FACTURA_TB_INSERTAR_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_CITA IN FIDE_FACTURA_TB.ID_CITA%TYPE,
P_FECHA_EMISION IN FIDE_FACTURA_TB.FECHA_EMISION%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
)IS
BEGIN
    INSERT INTO FIDE_FACTURA_TB(ID_FACTURA, ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, MONTO_TOTAL, ID_ESTADO)
    VALUES(P_ID_FACTURA, P_ID_CITA, P_FECHA_EMISION, P_SUBTOTAL, P_IVA, P_TOTAL, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Factura #' || P_ID_FACTURA || ' generada.');
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error generando factura: ' || SQLERRM);
END FIDE_FACTURA_TB_INSERTAR_SP;
-------------------------------------------------------------------------------------------------------------------   
PROCEDURE FIDE_FACTURA_TB_ANULAR_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_FACTURA_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_FACTURA = P_ID_FACTURA;
        
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Factura no encontrada.');
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Factura Anulada (Soft Delete).');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error anulando factura: ' || SQLERRM);
END FIDE_FACTURA_TB_ANULAR_SP;
---------------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_FACTURA_TB_LISTAR_SP(
    P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_FACTURA_TB;
EXCEPTION
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar facturas: ' || SQLERRM);
END FIDE_FACTURA_TB_LISTAR_SP;

PROCEDURE FIDE_ROL_SISTEMA_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ROL_SISTEMA_TB ORDER BY ID_ROL_SISTEMA ASC;
END FIDE_ROL_SISTEMA_TB_LISTAR_SP;


PROCEDURE FIDE_ESTADO_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ESTADO_TB ORDER BY ID_ESTADO ASC;
END FIDE_ESTADO_TB_LISTAR_SP;

PROCEDURE FIDE_DASHBOARD_SP(
P_CANT_SUCURSALES OUT NUMBER,
P_CANT_PERSONAL   OUT NUMBER,
P_CANT_USUARIOS   OUT NUMBER,
P_CANT_FACTURAS   OUT NUMBER
)IS
BEGIN
    -- 1. Contar Sucursales Activas
    SELECT COUNT(*) INTO P_CANT_SUCURSALES 
    FROM FIDE_SUCURSAL_TB 
    WHERE ID_ESTADO = 1;

     -- 2. Contar Personal Activo
    SELECT COUNT(*) INTO P_CANT_PERSONAL 
    FROM FIDE_PERSONAL_TB 
    WHERE ID_ESTADO = 1;

    -- 3. Contar Usuarios Activos
    SELECT COUNT(*) INTO P_CANT_USUARIOS 
    FROM FIDE_USUARIO_TB 
    WHERE ID_ESTADO = 1;

    -- 4. Contar Total de Facturas (Sin filtro de estado, historial completo)
    SELECT COUNT(*) INTO P_CANT_FACTURAS 
    FROM FIDE_FACTURA_TB;
        
EXCEPTION
    WHEN OTHERS THEN
        P_CANT_SUCURSALES := 0;
        P_CANT_PERSONAL := 0;
        P_CANT_USUARIOS := 0;
        P_CANT_FACTURAS := 0;
    DBMS_OUTPUT.PUT_LINE('Error obteniendo estadísticas: ' || SQLERRM);
END FIDE_DASHBOARD_SP;

------------------------------------------------------------------------------------------------------------------
-------FUNCIONES---------

FUNCTION FIDE_CALCULAR_VENTAS_SUCURSAL_FN(
    P_ID_SUCURSAL NUMBER
) RETURN NUMBER IS
        V_TOTAL_VENTAS NUMBER := 0;
    CURSOR C_FACTURAS IS
    SELECT F.MONTO_TOTAL 
    FROM FIDE_FACTURA_TB F
    JOIN FIDE_CITA_TB C ON F.ID_CITA = C.ID_CITA
    WHERE C.ID_SUCURSAL = P_ID_SUCURSAL AND F.ID_ESTADO = 1;
BEGIN
    FOR R_FACTURA IN C_FACTURAS LOOP
            V_TOTAL_VENTAS := V_TOTAL_VENTAS + R_FACTURA.MONTO_TOTAL;
    END LOOP;
    RETURN V_TOTAL_VENTAS;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en funcion ventas: ' || SQLERRM);
        RETURN 0;
END FIDE_CALCULAR_VENTAS_SUCURSAL_FN;
-----------------------------------------------------------------------------------------------------------------------
FUNCTION FIDE_CONTAR_PERSONAL_ROL_FN(
    P_ID_ROL NUMBER
) RETURN NUMBER IS
    V_CANTIDAD NUMBER := 0;
    CURSOR C_PERSONAL IS
        SELECT ID_ROL_PERSONAL FROM FIDE_PERSONAL_TB;
    BEGIN
    FOR R_PERSONAL IN C_PERSONAL LOOP
        IF (R_PERSONAL.ID_ROL_PERSONAL = P_ID_ROL) THEN
                V_CANTIDAD := V_CANTIDAD + 1;
        END IF;
    END LOOP;
    RETURN V_CANTIDAD;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en funcion contar: ' || SQLERRM);
    RETURN 0;
END FIDE_CONTAR_PERSONAL_ROL_FN;

FUNCTION FIDE_ALERGIAS_PACIENTES_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    -- Cursor de Pacientes
    CURSOR PACIENTES IS SELECT ID_PACIENTE, NOMBRE || ' ' || APELLIDO_PATERNO AS NOMBRE_COMPLETO FROM FIDE_PACIENTE_TB;
    -- Cursor de Alergias
    CURSOR ALERGIAS IS SELECT ID_PACIENTE FROM FIDE_PACIENTE_ALERGIA_TB;
BEGIN
    FOR PACIENTE IN PACIENTES LOOP
        V_CONTADOR := 0;

        FOR ALERGIA IN ALERGIAS LOOP
            IF (ALERGIA.ID_PACIENTE = PACIENTE.ID_PACIENTE) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ALERGIAS REGISTRADAS PARA EL PACIENTE: ' || 
            PACIENTE.NOMBRE_COMPLETO
        );
    END LOOP;

    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN FUNCION ALERGIAS: ' || SQLERRM);
        RETURN 0;
END FIDE_ALERGIAS_PACIENTES_FN;

------------------------------------------------------------

FUNCTION FIDE_CITAS_MEDICOS_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    -- Cursor de Medicos/Personal
    CURSOR MEDICOS IS SELECT ID_PERSONAL, NOMBRE || ' ' || APELLIDO_PATERNO AS NOMBRE_MEDICO FROM FIDE_PERSONAL_TB; 
    -- Cursor de Citas
    CURSOR CITAS IS SELECT ID_MEDICO FROM FIDE_CITA_TB;
BEGIN
    FOR MEDICO IN MEDICOS LOOP
        V_CONTADOR := 0;

        FOR CITA IN CITAS LOOP
            IF (CITA.ID_MEDICO = MEDICO.ID_PERSONAL) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        -- Opcional: Mostrar solo si tiene citas (quita el IF si quieres ver todos)
        IF V_CONTADOR >= 0 THEN 
            DBMS_OUTPUT.PUT_LINE(
                V_CONTADOR || ' CITAS PROGRAMADAS PARA EL MEDICO: ' || 
                MEDICO.NOMBRE_MEDICO
            );
        END IF;
    END LOOP;

    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN FUNCION CITAS MEDICOS: ' || SQLERRM);
        RETURN 0;
END FIDE_CITAS_MEDICOS_FN;

-------------------------------------------------------------------------------------------------------------------

FUNCTION FIDE_CITAS_SUCURSALES_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    -- Cursor de Sucursales
    CURSOR SUCURSALES IS SELECT ID_SUCURSAL, NOMBRE FROM FIDE_SUCURSAL_TB;
    -- Cursor de Citas
    CURSOR CITAS IS SELECT ID_SUCURSAL FROM FIDE_CITA_TB;
BEGIN
    FOR SUCURSAL IN SUCURSALES LOOP
        V_CONTADOR := 0;

        FOR CITA IN CITAS LOOP
            IF (CITA.ID_SUCURSAL = SUCURSAL.ID_SUCURSAL) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' CITAS REGISTRADAS EN LA SUCURSAL: ' || 
            SUCURSAL.NOMBRE
        );
    END LOOP;

    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN FUNCION CITAS SUCURSALES: ' || SQLERRM);
        RETURN 0;
END FIDE_CITAS_SUCURSALES_FN;

FUNCTION FIDE_DIRECCIONES_DISTRITOS_FN
RETURN NUMBER 
IS
    V_CONTADOR NUMBER := 0;
    CURSOR DISTRITOS IS SELECT ID_DISTRITO, NOMBRE_DISTRITO FROM FIDE_DISTRITOS_TB; 
    CURSOR DIRECCIONES IS SELECT ID_DISTRITO FROM FIDE_DIRECCIONES_TB; 
BEGIN

    FOR DISTRITO IN DISTRITOS LOOP
        V_CONTADOR:=0;

        FOR DIRECCION IN DIRECCIONES LOOP
            IF (DIRECCION.ID_DISTRITO = DISTRITO.ID_DISTRITO) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ' || 
            'DIRECCIONES EN EL DISTRITO ' || ' ' || 
            DISTRITO.NOMBRE_DISTRITO
        );
    END LOOP;

    RETURN 1; 

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN LA FUNCION: ' || SQLERRM);
        RETURN 0;
END FIDE_DIRECCIONES_DISTRITOS_FN;
-------------------------------------------------------------------------------------------------------
FUNCTION FIDE_DIRECCIONES_PACIENTES_FN
RETURN NUMBER 
IS
    V_CONTADOR NUMBER := 0;
    CURSOR PACIENTES IS SELECT * FROM FIDE_PACIENTE_TB;
    CURSOR DIRECCIONES IS SELECT ID_DIRECCION, DETALLES FROM FIDE_DIRECCIONES_TB; -- Asumo la columna DETALLES
BEGIN

    FOR DIRECCION IN DIRECCIONES LOOP
        V_CONTADOR:=0;

        FOR PACIENTE IN PACIENTES LOOP
            IF (PACIENTE.ID_DIRECCION = DIRECCION.ID_DIRECCION) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ' || 
            'PACIENTES EN LA DIRECCION ' || ' ' || 
            DIRECCION.DETALLES
        );
    END LOOP;
    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN LA FUNCION: ' || SQLERRM);
        RETURN 0;
END FIDE_DIRECCIONES_PACIENTES_FN;
--------------------------------------------------------------------------------------------------------
FUNCTION FIDE_ENFERMEDADES_PACIENTES_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    CURSOR ENFERMEDADES IS SELECT ID_ENFERMEDAD, NOMBRE_ENFERMEDAD FROM FIDE_ENFERMEDAD_CRONICA_TB;
    CURSOR PACIENTES IS SELECT ID_ENFERMEDAD FROM FIDE_PACIENTE_ENFERMEDAD_TB;
BEGIN
    FOR ENFERMEDAD IN ENFERMEDADES LOOP
        V_CONTADOR:=0;

        FOR PACIENTE IN PACIENTES LOOP
            IF (PACIENTE.ID_ENFERMEDAD = ENFERMEDAD.ID_ENFERMEDAD) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ' || 
            'PACIENTES CON LA ENFERMEDAD: ' || ' ' || 
            ENFERMEDAD.NOMBRE_ENFERMEDAD
        );
    END LOOP;
    RETURN 1;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        RETURN 0;
END FIDE_ENFERMEDADES_PACIENTES_FN;

END FIDE_SALUDTOTAL_PKG;

/
