/* PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL"          
FECHA DE CREACION: 11/11/25 
DESCRIPCION: CREACION DEL USUARIO CON SUS GRANTS
*/

CREATE USER FIDE_SALUDTOTAL_BD IDENTIFIED BY 123;
/
GRANT CREATE SESSION TO FIDE_SALUDTOTAL_BD;
/
GRANT RESOURCE TO FIDE_SALUDTOTAL_BD;
/
GRANT CREATE TABLE TO FIDE_SALUDTOTAL_BD;
/
GRANT CREATE VIEW TO FIDE_SALUDTOTAL_BD;
/
ALTER USER FIDE_SALUDTOTAL_BD QUOTA UNLIMITED ON USERS;

/* PROYECTO LENGUAJES DE BASE DE DATOS SALUD TOTAL          
FECHA DE CREACION: 18/11/25 
DESCRIPCION: CREACION DEL PAQUETE DE LA BD
*/

CREATE OR REPLACE PACKAGE FIDE_SALUDTOTAL_PKG AS 

END FIDE_SALUDTOTAL_PKG;
/

CREATE OR REPLACE PACKAGE BODY FIDE_SALUDTOTAL_PKG AS 

END FIDE_SALUDTOTAL_PKG;
/
/* PROYECTO LENGUAJES DE BASE DE DATOS SALUD TOTAL          
FECHA DE CREACION: 11/11/25 
DESCRIPCION: CREACION DE LAS TABLAS DE LA BD
*/
---TABLA MAESTRA DE ESTADOS
CREATE TABLE FIDE_ESTADO_TB(
ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADO_TB_ID_ESTADO_PK PRIMARY KEY,
NOMBRE_ESTADO VARCHAR2(40) NOT NULL,
DESCRIPCION VARCHAR2(200)
);
/
--MODULO DE DIRECCIONES
CREATE TABLE FIDE_PROVINCIAS_TB(
ID_PROVINCIA NUMBER CONSTRAINT FIDE_PROVINCIAS_TB_ID_PROVINCIA_PK PRIMARY KEY,
NOMBRE_PROVINCIA VARCHAR2(50) NOT NULL
);
/
CREATE TABLE FIDE_CANTONES_TB(
ID_CANTON NUMBER CONSTRAINT FIDE_CANTONES_TB_ID_CANTON_PK PRIMARY KEY,
NOMBRE_CANTON VARCHAR2(80) NOT NULL,
ID_PROVINCIA NUMBER NOT NULL CONSTRAINT FIDE_CANTONES_TB_ID_PROVINCIA_FK
    REFERENCES FIDE_PROVINCIAS_TB(ID_PROVINCIA)
);
/
CREATE TABLE FIDE_DISTRITOS_TB(
ID_DISTRITO NUMBER CONSTRAINT FIDE_DISTRITOS_TB_ID_DISTRITO_PK PRIMARY KEY,
NOMBRE_DISTRITO VARCHAR2(50) NOT NULL,
ID_CANTON NUMBER NOT NULL CONSTRAINT FIDE_DISTRITOS_TB_ID_CANTON_FK REFERENCES
    FIDE_CANTONES_TB(ID_CANTON)
);
/
CREATE TABLE FIDE_DIRECCIONES_TB(
ID_DIRECCION NUMBER CONSTRAINT FIDE_DIRECCIONES_TB_ID_DIRECCION_PK PRIMARY KEY,
ID_DISTRITO NUMBER NOT NULL CONSTRAINT FIDE_DIRECCIONES_TB_ID_DISTRITO_FK
    REFERENCES FIDE_DISTRITOS_TB(ID_DISTRITO),
DETALLES VARCHAR2(300) NOT NULL,
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_DIRECCIONES_TB_ID_ESTADO_FK REFERENCES
    FIDE_ESTADO_TB(ID_ESTADO)
);
/
--MODULO CATALOGOS INDEPENDIENTES
CREATE TABLE FIDE_ROL_PERSONAL_TB(
ID_ROL_PERSONAL NUMBER CONSTRAINT FIDE_ROL_PERSONAL_TB_ID_ROL_PERSONAL_PK PRIMARY KEY,
NOMBRE_ROL VARCHAR2(100) NOT NULL,
DESCIPCION VARCHAR2(220)
);
/
CREATE TABLE FIDE_ROL_SISTEMA_TB(
ID_ROL_SISTEMA NUMBER CONSTRAINT FIDE_ROL_SISTEMA_TB_ID_ROL_SISTEMA_PK PRIMARY KEY,
NOMBRE_ROL VARCHAR2(100) NOT NULL,
DESCIPCION VARCHAR2(220)
);
/
CREATE TABLE FIDE_ALERGIA_TB(
ID_ALERGIA NUMBER CONSTRAINT FIDE_ALERGIA_TB_ID_ALERGIA_PK PRIMARY KEY,
NOMBRE_ALERGIA VARCHAR2(100) NOT NULL
);
/
CREATE TABLE FIDE_ENFERMEDAD_CRONICA_TB(
ID_ENFERMEDAD NUMBER CONSTRAINT FIDE_ENFERMEDAD_CRONICA_TB_ID_ENFERMEDAD_PK PRIMARY KEY,
NOMBRE_ENFERMEDAD VARCHAR2(100) NOT NULL
);
/
CREATE TABLE FIDE_MEDICAMENTO_TB(
ID_MEDICAMENTO NUMBER CONSTRAINT FIDE_MEDICAMENTO_TB_ID_MEDICAMENTO_PK PRIMARY KEY,
NOMBRE_COMERCIAL VARCHAR2(50) NOT NULL,
PRINCIPIO_ACTIVO VARCHAR2(50),
PRESENTACION VARCHAR2(50)
);
/

--MODULO: GESTION DE SUCURSALES Y PERSONAL
CREATE TABLE FIDE_SUCURSAL_TB(
ID_SUCURSAL NUMBER CONSTRAINT FIDE_SUCURSAL_TB_ID_SUCURSAL_PK PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
ID_DIRECCION NUMBER NOT NULL CONSTRAINT FIDE_SUCURSAL_TB_ID_DIRECCION_FK REFERENCES 
    FIDE_DIRECCIONES_TB(ID_DIRECCION),
TELEFONO VARCHAR2(20),
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_SUCURSAL_TB_ID_ESTADO_FK
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE TABLE FIDE_PERSONAL_TB(
ID_PERSONAL NUMBER CONSTRAINT FIDE_PERSONAL_TB_ID_PERSONAL_PK PRIMARY KEY,
NOMBRE VARCHAR2(30) NOT NULL,
APELLIDO_PATERNO VARCHAR2(30) NOT NULL,
APELLIDO_MATERNO VARCHAR2(30),
FECHA_CONTRATACION DATE NOT NULL,
ID_SUCURSAL NUMBER NOT NULL CONSTRAINT FIDE_PERSONAL_TB_ID_SUCURSAL_FK
    REFERENCES FIDE_SUCURSAL_TB (ID_SUCURSAL),
ID_ROL_PERSONAL NUMBER NOT NULL CONSTRAINT FIDE_PERSONAL_TB_ID_ROL_PERSONAL_FK
    REFERENCES FIDE_ROL_PERSONAL_TB(ID_ROL_PERSONAL),
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_PERSONAL_TB_ID_ESTADO_FK
    REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);
/

---MODULO DE GESTION DE PACIENTES

CREATE TABLE FIDE_PACIENTE_TB(
ID_PACIENTE NUMBER CONSTRAINT FIDE_PACIENTE_TB_ID_PACIENTE_PK PRIMARY KEY,
NOMBRE VARCHAR2(30) NOT NULL,
APELLIDO_PATERNO VARCHAR2(30) NOT NULL,
APELLIDO_MATERNO VARCHAR2(30),
FECHA_NACIMIENTO DATE NOT NULL,
ID_DIRECCION NUMBER NOT NULL CONSTRAINT FIDE_PACIENTE_TB_ID_DIRECCION_FK
    REFERENCES FIDE_DIRECCIONES_TB (ID_DIRECCION),
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_PACIENTE_TB_ID_ESTADO_FK
    REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
);
/
CREATE TABLE FIDE_PACIENTE_ALERGIA_TB(
ID_PACIENTE NUMBER NOT NULL CONSTRAINT FIDE_PACIENTE_ALERGIA_TB_ID_PACIENTE_FK
    REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE),
ID_ALERGIA NUMBER NOT NULL CONSTRAINT FIDE_PACIENTE_ALERGIA_TB_ID_ALERGIA_FK
    REFERENCES FIDE_ALERGIA_TB(ID_ALERGIA), 
FECHA_DIAGNOSTICO DATE,
NIVEL_SEVERIDAD VARCHAR2(20) CONSTRAINT FIDE_PACIENTE_ALERGIA_TB_NIVEL_CHK
    CHECK (NIVEL_SEVERIDAD IN ('Leve','Moderada','Severa')),
NOTAS VARCHAR2(300),
CONSTRAINT FIDE_PACIENTE_ALERGIA_TB_PK PRIMARY KEY (ID_PACIENTE, ID_ALERGIA)
);
/
CREATE TABLE FIDE_PACIENTE_ENFERMEDAD_TB(
ID_PACIENTE NUMBER NOT NULL CONSTRAINT FIDE_PACIENTE_ENFERMEDAD_TB_ID_PACIENTE_FK
    REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE),
ID_ENFERMEDAD NUMBER NOT NULL CONSTRAINT FIDE_PACIENTE_ENFERMEDAD_TB_ID_ENFERMEDAD_FK
    REFERENCES FIDE_ENFERMEDAD_CRONICA_TB(ID_ENFERMEDAD), 
FECHA_DIAGNOSTICO DATE,
NOTAS VARCHAR2(300),
CONSTRAINT FIDE_PACIENTE_ENFERMEDAD_TB_PK PRIMARY KEY (ID_PACIENTE, ID_ENFERMEDAD)
);
/
--MODULO GESTION DE INVENTARIOS
CREATE TABLE FIDE_INVENTARIO_TB(
ID_INVENTARIO NUMBER CONSTRAINT FIDE_INVENTARIO_TB_ID_INVENTARIO_PK PRIMARY KEY,
ID_SUCURSAL NUMBER NOT NULL CONSTRAINT FIDE_INVENTARIO_TB_ID_SUCURSAL_FK
    REFERENCES FIDE_SUCURSAL_TB(ID_SUCURSAL),
ID_MEDICAMENTO NUMBER NOT NULL CONSTRAINT FIDE_INVENTARIO_TB_ID_MEDICAMENTO_FK
    REFERENCES FIDE_MEDICAMENTO_TB(ID_MEDICAMENTO),
STOCK NUMBER (6) NOT NULL,
FECHA_VENCIMIENTO DATE,
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_INVENTARIO_TB_ID_ESTADO_FK
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
--MODULO GESTION DE CITAS Y AGENDA
CREATE TABLE FIDE_CITA_TB(
ID_CITA NUMBER CONSTRAINT FIDE_CITA_TB_ID_CITA_PK PRIMARY KEY,
ID_PACIENTE NUMBER NOT NULL CONSTRAINT FIDE_CITA_TB_ID_PACIENTE_FK
    REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE),
ID_MEDICO NUMBER NOT NULL CONSTRAINT FIDE_CITA_TB_ID_MEDICO_FK
    REFERENCES FIDE_PERSONAL_TB(ID_PERSONAL),
ID_SUCURSAL NUMBER NOT NULL CONSTRAINT FIDE_CITA_TB_ID_SUCURSAL_FK
    REFERENCES FIDE_SUCURSAL_TB(ID_SUCURSAL),
FECHA_HORA_CITA TIMESTAMP NOT NULL,
MOTIVA_CONSULTA VARCHAR2(300),
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_CITA_TB_ID_ESTADO_FK
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
--MODULO HISTORIAL CLINICO Y FACTURACION

CREATE TABLE FIDE_HISTORIAL_CLINICO_TB(
ID_HISTORIAL NUMBER CONSTRAINT FIDE_HISTORIAL_TB_ID_HISTORIAL_PK PRIMARY KEY,
ID_CITA NUMBER NOT NULL CONSTRAINT FIDE_HISTORIAL_TB_ID_CITA_UNIQUE UNIQUE
    CONSTRAINT FIDE_HISTORIAL_TB_ID_CITA_FK REFERENCES FIDE_CITA_TB(ID_CITA),
DIAGNOSTICO VARCHAR2(600),
PROCEDIMIENTOS_REALIZADOS VARCHAR2(600),
TRATAMIENTO_SUGERIDO VARCHAR2(600)
);
/
CREATE TABLE FIDE_FACTURA_TB(
ID_FACTURA NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_FACTURA_PK PRIMARY KEY,
ID_CITA NUMBER NOT NULL CONSTRAINT FIDE_FACTURA_TB_ID_CITA_FK 
    REFERENCES FIDE_CITA_TB(ID_CITA),
FECHA_EMISION DATE NOT NULL,
SUBTOTAL DECIMAL(12,2)NOT NULL,
IVA DECIMAL(12,2) NOT NULL,
DESCUENTO_PORCENTAJE NUMBER(2) DEFAULT 0,
MONTO_TOTAL NUMBER (9,2) NOT NULL,
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_FACTURA_TB_ID_ESTADO_FK
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/
CREATE TABLE FIDE_FACTURA_DETALLE_TB(
ID_DETALLE NUMBER CONSTRAINT FIDE_FACTURA_DETALLE_TB_ID_DETALLE_PK PRIMARY KEY,
ID_FACTURA NUMBER NOT NULL CONSTRAINT FIDE_FACTURA_DETALLE_TB_ID_FACTURA_FK 
    REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
CONCEPTO VARCHAR2(50)NOT NULL,
ID_INVENTARIO NUMBER CONSTRAINT FIDE_FACTURA_DETALLE_TB_ID_INVENTARIO_FK
    REFERENCES FIDE_INVENTARIO_TB (ID_INVENTARIO),
CANTIDAD NUMBER (5) NOT NULL,
PRECIO_UNITARIO DECIMAL (9,2) NOT NULL,
SUBTOTAL DECIMAL (9,2)NOT NULL
);

---SEGURIDAD Y ACCESO

CREATE TABLE FIDE_USUARIO_TB(
ID_USUARIO NUMBER CONSTRAINT FIDE_USUARIO_TB_ID_USUARIO_PK PRIMARY KEY,
NOMBRE_USUARIO VARCHAR2(50) NOT NULL CONSTRAINT FIDE_USUARIO_TB_NOMBRE_USUARIO_UQ UNIQUE,
CONTRASENNA VARCHAR2(100) NOT NULL,
ID_PERSONAL NUMBER CONSTRAINT FIDE_USUARIO_TB_ID_PERSONAL_UQ UNIQUE
    CONSTRAINT FIDE_USUARIO_TB_ID_PERSONAL_FK REFERENCES FIDE_PERSONAL_TB(ID_PERSONAL),
ID_PACIENTE NUMBER CONSTRAINT FIDE_USUARIO_TB_ID_PACIENTE_UQ UNIQUE
    CONSTRAINT FIDE_USUARIO_TB_ID_PACIENTE_FK REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE),
ID_ROL_SISTEMA NUMBER CONSTRAINT FIDE_USUARIO_TB_ID_ROL_SISTEMA_FK REFERENCES FIDE_ROL_SISTEMA_TB(ID_ROL_SISTEMA),
ID_ESTADO NUMBER NOT NULL CONSTRAINT FIDE_USUARIO_TB_ID_ESTADO_FK
    REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);