--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-20-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package FIDE_SALUDTOTAL_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "FIDE_SALUDTOTAL_BD"."FIDE_SALUDTOTAL_PKG" AS 


PROCEDURE FIDE_ALERGIA_INSERT_SP(
P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_NOMBRE_ALERGIA IN FIDE_ALERGIA_TB.NOMBRE_ALERGIA%TYPE
);
------------------------------------------------------
PROCEDURE FIDE_CITA_DELETE_SP(
P_ID_CITA IN FIDE_CITA_TB.ID_CITA%TYPE,
P_ID_PACIENTE IN FIDE_CITA_TB.ID_PACIENTE%TYPE,
P_ID_MEDICO IN FIDE_CITA_TB.ID_MEDICO%TYPE,
P_ID_SUCURSAL IN FIDE_CITA_TB.ID_SUCURSAL%TYPE,
P_FECHA_HORA_CITA IN FIDE_CITA_TB.FECHA_HORA_CITA%TYPE,
P_MOTIVA_CONSULTA IN FIDE_CITA_TB.MOTIVA_CONSULTA%TYPE,
P_ID_ESTADO IN FIDE_CITA_TB.ID_ESTADO%TYPE
);
------------------------------------------------------
PROCEDURE FIDE_CITA_INSERT_SP(
P_ID_CITA IN FIDE_CITA_TB.ID_CITA%TYPE,
P_ID_PACIENTE IN FIDE_CITA_TB.ID_PACIENTE%TYPE,
P_ID_MEDICO IN FIDE_CITA_TB.ID_MEDICO%TYPE,
P_ID_SUCURSAL IN FIDE_CITA_TB.ID_SUCURSAL%TYPE,
P_FECHA_HORA_CITA IN FIDE_CITA_TB.FECHA_HORA_CITA%TYPE,
P_MOTIVA_CONSULTA IN FIDE_CITA_TB.MOTIVA_CONSULTA%TYPE,
P_ID_ESTADO IN FIDE_CITA_TB.ID_ESTADO%TYPE
);
-------------------------------------------------------
PROCEDURE FIDE_ENFERMEDAD_CRONICA_INSERT_SP(
P_ID_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.ID_ENFERMEDAD%TYPE,
P_NOMBRE_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.NOMBRE_ENFERMEDAD%TYPE
);
-------------------------------------------------------
PROCEDURE FIDE_HISTORIAL_CLINICO_INSERT_SP(
P_ID_HISTORIAL IN FIDE_HISTORIAL_CLINICO_TB.ID_HISTORIAL%TYPE,
P_ID_CITA IN FIDE_HISTORIAL_CLINICO_TB.ID_CITA%TYPE,
P_DIAGNOSTICO IN FIDE_HISTORIAL_CLINICO_TB.DIAGNOSTICO%TYPE,
P_PROCEDIMIENTOS_REALIZADOS IN FIDE_HISTORIAL_CLINICO_TB.PROCEDIMIENTOS_REALIZADOS%TYPE,
P_TRATAMIENTO_SUGERIDO IN FIDE_HISTORIAL_CLINICO_TB.TRATAMIENTO_SUGERIDO%TYPE
);
-------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ALERGIA_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ALERGIA_TB.ID_PACIENTE%TYPE,
P_ID_ALERGIA IN FIDE_PACIENTE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ALERGIA_TB.FECHA_DIAGNOSTICO%TYPE,
P_NIVEL_SEVERIDAD IN FIDE_PACIENTE_ALERGIA_TB.NIVEL_SEVERIDAD%TYPE,
P_NOTAS IN FIDE_PACIENTE_ALERGIA_TB.NOTAS%TYPE
);
-------------------------------------------------------
PROCEDURE FIDE_PACIENTE_DELETE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE
);
-------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ENFERMEDAD_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_PACIENTE%TYPE,
P_ID_ENFERMEDAD IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_ENFERMEDAD%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ENFERMEDAD_TB.FECHA_DIAGNOSTICO%TYPE,
P_NOTAS IN FIDE_PACIENTE_ENFERMEDAD_TB.NOTAS%TYPE
);
-------------------------------------------------------
PROCEDURE FIDE_PACIENTE_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE,
P_NOMBRE IN FIDE_PACIENTE_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PACIENTE_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PACIENTE_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_NACIMIENTO IN FIDE_PACIENTE_TB.FECHA_NACIMIENTO%TYPE,
P_ID_DIRECCION IN FIDE_PACIENTE_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN FIDE_PACIENTE_TB.ID_ESTADO%TYPE
);
-------------------------------------------------------
PROCEDURE FIDE_PACIENTE_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE,
P_NOMBRE IN FIDE_PACIENTE_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PACIENTE_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PACIENTE_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_NACIMIENTO IN FIDE_PACIENTE_TB.FECHA_NACIMIENTO%TYPE,
P_ID_DIRECCION IN FIDE_PACIENTE_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN FIDE_PACIENTE_TB.ID_ESTADO%TYPE
);
--------------------------------------------------------
PROCEDURE FIDE_PACIENTE_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
);
--------------------------------------------------------
PROCEDURE FIDE_CITA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
);
--------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ENFERMEDAD_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
);
--------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ALERGIA_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ALERGIA_TB.ID_PACIENTE%TYPE,
P_ID_ALERGIA IN FIDE_PACIENTE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ALERGIA_TB.FECHA_DIAGNOSTICO%TYPE,
P_NIVEL_SEVERIDAD IN FIDE_PACIENTE_ALERGIA_TB.NIVEL_SEVERIDAD%TYPE,
P_NOTAS IN FIDE_PACIENTE_ALERGIA_TB.NOTAS%TYPE
);
----------------------------------------------------------
PROCEDURE FIDE_HISTORIAL_CLINICO_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
);
-----------------------------------------------------------
PROCEDURE FIDE_HISTORIAL_CLINICO_UPDATE_SP(
P_ID_HISTORIAL IN FIDE_HISTORIAL_CLINICO_TB.ID_HISTORIAL%TYPE,
P_ID_CITA IN FIDE_HISTORIAL_CLINICO_TB.ID_CITA%TYPE,
P_DIAGNOSTICO IN FIDE_HISTORIAL_CLINICO_TB.DIAGNOSTICO%TYPE,
P_PROCEDIMIENTOS_REALIZADOS IN FIDE_HISTORIAL_CLINICO_TB.PROCEDIMIENTOS_REALIZADOS%TYPE,
P_TRATAMIENTO_SUGERIDO IN FIDE_HISTORIAL_CLINICO_TB.TRATAMIENTO_SUGERIDO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
);
------------------------------------------------------------
PROCEDURE FIDE_PACIENTE_ENFERMEDAD_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_PACIENTE%TYPE,
P_ID_ENFERMEDAD IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_ENFERMEDAD%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ENFERMEDAD_TB.FECHA_DIAGNOSTICO%TYPE,
P_NOTAS IN FIDE_PACIENTE_ENFERMEDAD_TB.NOTAS%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_UPDATE_SP(
P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_NOMBRE_ALERGIA IN FIDE_ALERGIA_TB.NOMBRE_ALERGIA%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_ENFERMEDAD_CRONICA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
);
------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_UPDATE_SP(
P_ID_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.ID_ENFERMEDAD%TYPE,
P_NOMBRE_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.NOMBRE_ENFERMEDAD%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_SUCURSAL_TB_INSERTAR_SP(
P_NOMBRE IN FIDE_SUCURSAL_TB.NOMBRE%TYPE,
P_ID_DIRECCION IN FIDE_SUCURSAL_TB.ID_DIRECCION%TYPE,
P_TELEFONO IN FIDE_SUCURSAL_TB.TELEFONO%TYPE,
P_ID_ESTADO IN FIDE_SUCURSAL_TB.ID_ESTADO%TYPE
);
 ------------------------------------------------------------   
PROCEDURE FIDE_SUCURSAL_TB_ACTUALIZAR_SP
(
P_ID_SUCURSAL IN FIDE_SUCURSAL_TB.ID_SUCURSAL%TYPE,
P_NOMBRE IN FIDE_SUCURSAL_TB.NOMBRE%TYPE,
P_ID_DIRECCION IN FIDE_SUCURSAL_TB.ID_DIRECCION%TYPE,
P_TELEFONO IN FIDE_SUCURSAL_TB.TELEFONO%TYPE
);
------------------------------------------------------------    
PROCEDURE FIDE_SUCURSAL_TB_ELIMINAR_SP(
P_ID_SUCURSAL IN FIDE_SUCURSAL_TB.ID_SUCURSAL%TYPE,
P_ID_ESTADO IN FIDE_SUCURSAL_TB.ID_ESTADO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_SUCURSAL_TB_LISTAR_SP(
P_CURSOR OUT SYS_REFCURSOR
);

------------------------------------------------------------
PROCEDURE FIDE_PERSONAL_TB_INSERTAR_SP(
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_NOMBRE IN FIDE_PERSONAL_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PERSONAL_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PERSONAL_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_CONTRATACION IN FIDE_PERSONAL_TB.FECHA_CONTRATACION%TYPE,
P_ID_SUCURSAL IN FIDE_PERSONAL_TB.ID_SUCURSAL%TYPE,
P_ID_ROL_PERSONAL IN FIDE_PERSONAL_TB.ID_ROL_PERSONAL%TYPE,
P_ID_ESTADO IN FIDE_PERSONAL_TB.ID_ESTADO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_PERSONAL_TB_ACTUALIZAR_SP( 
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_NOMBRE IN FIDE_PERSONAL_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PERSONAL_TB.APELLIDO_PATERNO%TYPE,
P_ID_SUCURSAL IN FIDE_PERSONAL_TB.ID_SUCURSAL%TYPE,
P_ID_ROL_PERSONAL IN FIDE_PERSONAL_TB.ID_ROL_PERSONAL%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_PERSONAL_TB_ELIMINAR_SP(
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_ID_ESTADO IN FIDE_PERSONAL_TB.ID_ESTADO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_PERSONAL_TB_LISTAR_SP(
P_CURSOR OUT SYS_REFCURSOR
);

------------------------------------------------------------
PROCEDURE FIDE_USUARIO_TB_INSERTAR_SP(
P_NOMBRE_USUARIO IN FIDE_USUARIO_TB.NOMBRE_USUARIO%TYPE,
P_CONTRASENNA IN FIDE_USUARIO_TB.CONTRASENNA%TYPE,
P_ID_PERSONAL IN FIDE_USUARIO_TB.ID_PERSONAL%TYPE,
P_ID_PACIENTE IN FIDE_USUARIO_TB.ID_PACIENTE%TYPE,
P_ID_ROL_SISTEMA IN FIDE_USUARIO_TB.ID_ROL_SISTEMA%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_USUARIO_TB_ACTUALIZAR_SP( -- NUEVO (Actualizar Rol o Estado)
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_ID_ROL_SISTEMA IN FIDE_USUARIO_TB.ID_ROL_SISTEMA%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_USUARIO_TB_CAMBIAR_CLAVE_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NUEVA_CONTRASENNA IN FIDE_USUARIO_TB.CONTRASENNA%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_USUARIO_TB_LISTAR_SP( 
P_CURSOR OUT SYS_REFCURSOR
);
------------------------------------------------------------

PROCEDURE FIDE_FACTURA_TB_INSERTAR_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_CITA IN FIDE_FACTURA_TB.ID_CITA%TYPE,
P_FECHA_EMISION IN FIDE_FACTURA_TB.FECHA_EMISION%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_FACTURA_TB_ANULAR_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
);
------------------------------------------------------------
PROCEDURE FIDE_FACTURA_TB_LISTAR_SP(
P_CURSOR OUT SYS_REFCURSOR
);

PROCEDURE FIDE_ROL_SISTEMA_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR);

PROCEDURE FIDE_ESTADO_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR);

PROCEDURE FIDE_DASHBOARD_SP(
P_CANT_SUCURSALES OUT NUMBER,
P_CANT_PERSONAL   OUT NUMBER,
P_CANT_USUARIOS   OUT NUMBER,
P_CANT_FACTURAS   OUT NUMBER
);

------------------------------------------------------------

FUNCTION FIDE_CALCULAR_VENTAS_SUCURSAL_FN(P_ID_SUCURSAL NUMBER) 
RETURN NUMBER;
------------------------------------------------------------
FUNCTION FIDE_CONTAR_PERSONAL_ROL_FN(P_ID_ROL NUMBER)
RETURN NUMBER;
------------------------------------------------------------

FUNCTION FIDE_ALERGIAS_PACIENTES_FN
RETURN NUMBER;

------------------------------------------------------------
FUNCTION FIDE_CITAS_MEDICOS_FN
RETURN NUMBER;

---------------------------------------------------------------

FUNCTION FIDE_CITAS_SUCURSALES_FN
RETURN NUMBER;
----------------------------------------------------
FUNCTION FIDE_DIRECCIONES_DISTRITOS_FN
RETURN NUMBER;
----------------------------------------------------
FUNCTION FIDE_DIRECCIONES_PACIENTES_FN
RETURN NUMBER;
----------------------------------------------------
FUNCTION FIDE_ENFERMEDADES_PACIENTES_FN
RETURN NUMBER;

END FIDE_SALUDTOTAL_PKG;

/
