/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: INSERTS PARA EL BLOQUE 1 (CATALOGOS MAESTROS)
-- Este script asume que los IDs son numéricos y se están insertando manualmente.
-- Si usas secuencias, deberás reemplazar los números de ID con 'NOMBRE_SECUENCIA.NEXTVAL'.
*/

-- 1. FIDE_ESTADO_TB (La tabla maestra más importante)
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION) VALUES (1, 'Activo', 'El registro está activo y operativo.');
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION) VALUES (2, 'Inactivo', 'El registro está inactivo (borrado lógico).');
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION) VALUES (3, 'Pendiente', 'El registro está pendiente de aprobación o ejecución (ej. Cita pendiente).');
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION) VALUES (4, 'Completado', 'La acción se completó satisfactoriamente (ej. Cita completada).');
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION) VALUES (5, 'Anulado', 'El registro ha sido anulado (ej. Factura anulada).');

-- 2. FIDE_ROL_PERSONAL_TB (Roles dentro de la clínica)
INSERT INTO FIDE_ROL_PERSONAL_TB (ID_ROL_PERSONAL, NOMBRE_ROL, DESCIPCION) VALUES (1, 'Médico General', 'Personal médico con atención primaria.');
INSERT INTO FIDE_ROL_PERSONAL_TB (ID_ROL_PERSONAL, NOMBRE_ROL, DESCIPCION) VALUES (2, 'Médico Especialista', 'Personal médico con una especialidad (Cardiología, Dermatología, etc.).');
INSERT INTO FIDE_ROL_PERSONAL_TB (ID_ROL_PERSONAL, NOMBRE_ROL, DESCIPCION) VALUES (3, 'Enfermero/a', 'Personal de enfermería y asistencia médica.');
INSERT INTO FIDE_ROL_PERSONAL_TB (ID_ROL_PERSONAL, NOMBRE_ROL, DESCIPCION) VALUES (4, 'Recepcionista', 'Personal de atención al cliente y agendamiento de citas.');
INSERT INTO FIDE_ROL_PERSONAL_TB (ID_ROL_PERSONAL, NOMBRE_ROL, DESCIPCION) VALUES (5, 'Administrativo', 'Personal de administración y finanzas.');

-- 3. FIDE_ROL_SISTEMA_TB (Roles de acceso al software)
INSERT INTO FIDE_ROL_SISTEMA_TB (ID_ROL_SISTEMA, NOMBRE_ROL, DESCIPCION) VALUES (1, 'Administrador General', 'Acceso total al sistema.');
INSERT INTO FIDE_ROL_SISTEMA_TB (ID_ROL_SISTEMA, NOMBRE_ROL, DESCIPCION) VALUES (2, 'Personal Médico', 'Acceso a historial clínico, agenda y recetas.');
INSERT INTO FIDE_ROL_SISTEMA_TB (ID_ROL_SISTEMA, NOMBRE_ROL, DESCIPCION) VALUES (3, 'Personal Recepción', 'Acceso a agenda, facturación y gestión de pacientes.');
INSERT INTO FIDE_ROL_SISTEMA_TB (ID_ROL_SISTEMA, NOMBRE_ROL, DESCIPCION) VALUES (4, 'Paciente', 'Acceso limitado para ver sus citas e historial.');

-- 4. FIDE_ALERGIA_TB (Catálogo de alergias comunes)
INSERT INTO FIDE_ALERGIA_TB (ID_ALERGIA, NOMBRE_ALERGIA) VALUES (1, 'Penicilina');
INSERT INTO FIDE_ALERGIA_TB (ID_ALERGIA, NOMBRE_ALERGIA) VALUES (2, 'AINE');
INSERT INTO FIDE_ALERGIA_TB (ID_ALERGIA, NOMBRE_ALERGIA) VALUES (3, 'Mariscos');
INSERT INTO FIDE_ALERGIA_TB (ID_ALERGIA, NOMBRE_ALERGIA) VALUES (4, 'Maní (Cacahuete)');
INSERT INTO FIDE_ALERGIA_TB (ID_ALERGIA, NOMBRE_ALERGIA) VALUES (5, 'Lactosa');
INSERT INTO FIDE_ALERGIA_TB (ID_ALERGIA, NOMBRE_ALERGIA) VALUES (6, 'Polvo / Ácaros');
INSERT INTO FIDE_ALERGIA_TB (ID_ALERGIA, NOMBRE_ALERGIA) VALUES (7, 'Sulfamidas');

-- 5. FIDE_ENFERMEDAD_CRONICA_TB (Catálogo de enfermedades crónicas)
INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB (ID_ENFERMEDAD, NOMBRE_ENFERMEDAD) VALUES (1, 'Hipertensión Arterial');
INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB (ID_ENFERMEDAD, NOMBRE_ENFERMEDAD) VALUES (2, 'Diabetes Mellitus Tipo 2');
INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB (ID_ENFERMEDAD, NOMBRE_ENFERMEDAD) VALUES (3, 'Asma Bronquial');
INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB (ID_ENFERMEDAD, NOMBRE_ENFERMEDAD) VALUES (4, 'Hipotiroidismo');
INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB (ID_ENFERMEDAD, NOMBRE_ENFERMEDAD) VALUES (5, 'Dislipidemia (Colesterol Alto)');
INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB (ID_ENFERMEDAD, NOMBRE_ENFERMEDAD) VALUES (6, 'Artritis Reumatoide');
INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB (ID_ENFERMEDAD, NOMBRE_ENFERMEDAD) VALUES (7, 'Diabetes Mellitus Tipo 1');

-- 6. FIDE_MEDICAMENTO_TB (Catálogo de medicamentos)
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (1, 'Tylenol', 'Acetaminofén', 'Tableta 500mg');
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (2, 'Advil', 'Ibuprofeno', 'Tableta 400mg');
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (3, 'Amoxil', 'Amoxicilina', 'Cápsula 500mg');
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (4, 'Cozaar', 'Losartán Potásico', 'Tableta 50mg');
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICamento, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (5, 'Glucophage', 'Metformina', 'Tableta 850mg');
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (6, 'Ventolin', 'Salbutamol', 'Inhalador 100mcg/dosis');
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (7, 'Eutirox', 'Levotiroxina', 'Tableta 100mcg');
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) VALUES (8, 'Lipitor', 'Atorvastatina', 'Tableta 20mg');

COMMIT;

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: INSERTS PARA EL BLOQUE 2 (ESTRUCTURA GEOGRAFICA)
-- NOTA: ID_ESTADO = 1 (Activo) fue creado en el Bloque 1.
*/

-- 7. FIDE_PROVINCIAS_TB (Las 7 Provincias de Costa Rica - Sin cambios)
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (1, 'San José');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (2, 'Alajuela');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (3, 'Cartago');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (4, 'Heredia');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (5, 'Guanacaste');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (6, 'Puntarenas');
INSERT INTO FIDE_PROVINCIAS_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (7, 'Limón');

-- 8. FIDE_CANTONES_TB (Al menos 3 por provincia)
-- San José (ID_PROVINCIA = 1)
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (1, 'San José', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (2, 'Escazú', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (3, 'Desamparados', 1);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (4, 'Montes de Oca', 1);
-- Alajuela (ID_PROVINCIA = 2)
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (5, 'Alajuela', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (6, 'San Ramón', 2);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (7, 'San Carlos', 2);
-- Cartago (ID_PROVINCIA = 3)
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (8, 'Cartago', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (9, 'Paraíso', 3);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (10, 'La Unión', 3);
-- Heredia (ID_PROVINCIA = 4)
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (11, 'Heredia', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (12, 'Santo Domingo', 4);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (13, 'Barva', 4);
-- Guanacaste (ID_PROVINCIA = 5)
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (14, 'Liberia', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (15, 'Nicoya', 5);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (16, 'Santa Cruz', 5);
-- Puntarenas (ID_PROVINCIA = 6)
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (17, 'Puntarenas', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (18, 'Esparza', 6);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (19, 'Osa', 6);
-- Limón (ID_PROVINCIA = 7)
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (20, 'Limón', 7);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (21, 'Pococí', 7);
INSERT INTO FIDE_CANTONES_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (22, 'Talamanca', 7);

-- 9. FIDE_DISTRITOS_TB (Al menos 3 por provincia)
-- San José (ID_CANTON = 1, 4)
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (1, 'Carmen', 1);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (2, 'Merced', 1);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (3, 'Mata Redonda', 1);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (4, 'San Pedro', 4);
-- Alajuela (ID_CANTON = 5, 6, 7)
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (5, 'Alajuela', 5);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (6, 'Santiago', 6);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (7, 'Quesada', 7);
-- Cartago (ID_CANTON = 8, 9, 10)
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (8, 'Oriental', 8);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (9, 'Paraíso', 9);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10, 'Tres Ríos', 10);
-- Heredia (ID_CANTON = 11, 12, 13)
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11, 'Heredia', 11);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12, 'Santo Domingo', 12);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (13, 'Barva', 13);
-- Guanacaste (ID_CANTON = 14, 15, 16)
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (14, 'Liberia', 14);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (15, 'Nicoya', 15);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (16, 'Santa Cruz', 16);
-- Puntarenas (ID_CANTON = 17, 18, 19)
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (17, 'Puntarenas', 17);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (18, 'Espíritu Santo', 18);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (19, 'Puerto Cortés', 19);
-- Limón (ID_CANTON = 20, 21, 22)
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20, 'Limón', 20);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21, 'Guápiles', 21);
INSERT INTO FIDE_DISTRITOS_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (22, 'Sixaola', 22);

-- 10. FIDE_DIRECCIONES_TB (Direcciones de ejemplo usando los distritos nuevos. ID_ESTADO = 1 (Activo))
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (1, 3, 'Sabana Sur, del Edificio de la Contraloría, 400 metros sur y 100 este, edificio esquinero color azul.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (2, 4, 'Costado este de la Iglesia de San Pedro, frente al Parque Kennedy.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (3, 5, 'Del Parque Central de Alajuela, 200 metros norte, sobre la Avenida 2.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (4, 11, 'Heredia centro, de la entrada principal de la Universidad Nacional, 100 metros oeste.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (5, 14, 'Liberia centro, 50 metros sur del Parque Central.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (6, 2, 'Barrio Chino, Avenida Segunda, contiguo al Restaurante Dragón Dorado.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (7, 10, 'Condominio El Cielito, 200m este de Terramall, Tres Ríos.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (8, 8, 'Cartago, del Mercado Central, 100 metros este, frente a la farmacia.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (9, 7, 'Ciudad Quesada, 1km al norte del Hospital San Carlos.', 1);
INSERT INTO FIDE_DIRECCIONES_TB (ID_DIRECCION, ID_DISTRITO, DETALLES, ID_ESTADO) VALUES (10, 15, 'Nicoya, 500m sur del parque, casa con portón rojo.', 1);

COMMIT;

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: INSERTS PARA EL BLOQUE 3 (SUCURSALES Y PERSONAL)
-- IDs de referencia usados:
-- FIDE_ESTADO_TB: 1 (Activo)
-- FIDE_DIRECCIONES_TB: 1 (Sabana Sur), 2 (San Pedro), 3 (Alajuela), 4 (Heredia)
-- FIDE_ROL_PERSONAL_TB: 1 (Médico General), 2 (Médico Especialista), 3 (Enfermero/a), 4 (Recepcionista), 5 (Administrativo)
*/

-- 11. FIDE_SUCURSAL_TB (Creación de las clínicas físicas)
INSERT INTO FIDE_SUCURSAL_TB (ID_SUCURSAL, NOMBRE, ID_DIRECCION, TELEFONO, ID_ESTADO) VALUES (1, 'SaludTotal Sede Sabana', 1, '2250-1010', 1);
INSERT INTO FIDE_SUCURSAL_TB (ID_SUCURSAL, NOMBRE, ID_DIRECCION, TELEFONO, ID_ESTADO) VALUES (2, 'SaludTotal Sede San Pedro', 2, '2250-2020', 1);
INSERT INTO FIDE_SUCURSAL_TB (ID_SUCURSAL, NOMBRE, ID_DIRECCION, TELEFONO, ID_ESTADO) VALUES (3, 'SaludTotal Sede Alajuela', 3, '2440-3030', 1);
INSERT INTO FIDE_SUCURSAL_TB (ID_SUCURSAL, NOMBRE, ID_DIRECCION, TELEFONO, ID_ESTADO) VALUES (4, 'SaludTotal Sede Heredia', 4, '2260-4040', 1);

-- 12. FIDE_PERSONAL_TB (Creación del personal)
-- Personal de Sede Sabana (ID_SUCURSAL = 1)
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (1, 'Carlos', 'Mora', 'Valverde', TO_DATE('2020-05-15', 'YYYY-MM-DD'), 1, 5, 1); -- Administrativo
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (2, 'Lucía', 'Fernández', 'Gómez', TO_DATE('2021-02-10', 'YYYY-MM-DD'), 1, 4, 1); -- Recepcionista
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (3, 'Miguel', 'Arias', 'Sánchez', TO_DATE('2020-07-01', 'YYYY-MM-DD'), 1, 1, 1); -- Médico General
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (4, 'Elena', 'Rojas', 'Mendoza', TO_DATE('2021-01-20', 'YYYY-MM-DD'), 1, 2, 1); -- Médico Especialista (Cardiología)
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (5, 'David', 'Castro', 'Pérez', TO_DATE('2022-03-05', 'YYYY-MM-DD'), 1, 3, 1); -- Enfermero

-- Personal de Sede San Pedro (ID_SUCURSAL = 2)
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (6, 'Sofía', 'Jiménez', 'Solano', TO_DATE('2022-01-15', 'YYYY-MM-DD'), 2, 4, 1); -- Recepcionista
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (7, 'Andrés', 'Vega', 'Campos', TO_DATE('2022-02-01', 'YYYY-MM-DD'), 2, 1, 1); -- Médico General
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (8, 'Valeria', 'Núñez', 'Salas', TO_DATE('2022-06-10', 'YYYY-MM-DD'), 2, 3, 1); -- Enfermera

-- Personal de Sede Alajuela (ID_SUCURSAL = 3)
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (9, 'Roberto', 'Chaves', 'Díaz', TO_DATE('2023-01-20', 'YYYY-MM-DD'), 3, 4, 1); -- Recepcionista
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (10, 'Ana', 'Hernández', 'Mora', TO_DATE('2023-02-01', 'YYYY-MM-DD'), 3, 1, 1); -- Médico General

-- Personal de Sede Heredia (ID_SUCURSAL = 4)
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (11, 'Gabriela', 'López', 'Acuña', TO_DATE('2023-05-10', 'YYYY-MM-DD'), 4, 4, 1); -- Recepcionista
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (12, 'Luis', 'Ramírez', 'Guzmán', TO_DATE('2023-06-01', 'YYYY-MM-DD'), 4, 2, 1); -- Médico Especialista (Dermatología)
INSERT INTO FIDE_PERSONAL_TB (ID_PERSONAL, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO) 
VALUES (13, 'Daniela', 'Vargas', 'Brenes', TO_DATE('2023-07-15', 'YYYY-MM-DD'), 4, 3, 1); -- Enfermera

COMMIT;

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: INSERTS PARA EL BLOQUE 4 (PACIENTES Y EXPEDIENTE BASICO)
-- IDs de referencia usados:
-- FIDE_ESTADO_TB: 1 (Activo)
-- FIDE_DIRECCIONES_TB: 5-10 (Direcciones de ejemplo creadas en Bloque 2)
-- FIDE_ALERGIA_TB: 1 (Penicilina), 2 (AINEs), 3 (Mariscos), 4 (Maní)
-- FIDE_ENFERMEDAD_CRONICA_TB: 1 (Hipertensión), 2 (Diabetes), 3 (Asma)
*/

-- 13. FIDE_PACIENTE_TB (Creación de pacientes)
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (1, 'Ana', 'Soto', 'Campos', TO_DATE('1990-03-15', 'YYYY-MM-DD'), 5, 1);
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (2, 'Bruno', 'Díaz', 'Rojas', TO_DATE('1985-11-20', 'YYYY-MM-DD'), 6, 1);
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (3, 'Carla', 'Vega', 'Muñoz', TO_DATE('2001-07-02', 'YYYY-MM-DD'), 7, 1);
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (4, 'Daniel', 'Gómez', 'Araya', TO_DATE('1972-01-30', 'YYYY-MM-DD'), 8, 1);
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (5, 'Esteban', 'Pérez', 'Salas', TO_DATE('1995-09-12', 'YYYY-MM-DD'), 9, 1);
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (6, 'Fabiana', 'López', 'Mora', TO_DATE('1988-06-05', 'YYYY-MM-DD'), 10, 1);
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (7, 'Gabriel', 'Jiménez', 'Solano', TO_DATE('1965-04-25', 'YYYY-MM-DD'), 1, 1);
INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
VALUES (8, 'Hilda', 'Morales', 'Castro', TO_DATE('1959-12-10', 'YYYY-MM-DD'), 3, 1);

-- 14. FIDE_PACIENTE_ALERGIA_TB (Asignación de alergias a pacientes)
-- Paciente 2 (Bruno) es alérgico a la Penicilina
INSERT INTO FIDE_PACIENTE_ALERGIA_TB (ID_PACIENTE, ID_ALERGIA, FECHA_DIAGNOSTICO, NIVEL_SEVERIDAD, NOTAS)
VALUES (2, 1, TO_DATE('2010-05-20', 'YYYY-MM-DD'), 'Severa', 'Anafilaxia reportada en la infancia.');
-- Paciente 4 (Daniel) es alérgico a los AINEs
INSERT INTO FIDE_PACIENTE_ALERGIA_TB (ID_PACIENTE, ID_ALERGIA, FECHA_DIAGNOSTICO, NIVEL_SEVERIDAD, NOTAS)
VALUES (4, 2, TO_DATE('2018-01-10', 'YYYY-MM-DD'), 'Moderada', 'Causa urticaria y problemas gástricos.');
-- Paciente 4 (Daniel) también es alérgico a los Mariscos
INSERT INTO FIDE_PACIENTE_ALERGIA_TB (ID_PACIENTE, ID_ALERGIA, FECHA_DIAGNOSTICO, NIVEL_SEVERIDAD, NOTAS)
VALUES (4, 3, TO_DATE('2005-02-01', 'YYYY-MM-DD'), 'Severa', 'Edema de glotis.');
-- Paciente 6 (Fabiana) es alérgica al Maní
INSERT INTO FIDE_PACIENTE_ALERGIA_TB (ID_PACIENTE, ID_ALERGIA, FECHA_DIAGNOSTICO, NIVEL_SEVERIDAD, NOTAS)
VALUES (6, 4, TO_DATE('1990-07-15', 'YYYY-MM-DD'), 'Leve', 'Solo causa picazón leve.');

-- 15. FIDE_PACIENTE_ENFERMEDAD_TB (Asignación de enfermedades crónicas)
-- Paciente 4 (Daniel) tiene Hipertensión
INSERT INTO FIDE_PACIENTE_ENFERMEDAD_TB (ID_PACIENTE, ID_ENFERMEDAD, FECHA_DIAGNOSTICO, NOTAS)
VALUES (4, 1, TO_DATE('2015-03-01', 'YYYY-MM-DD'), 'Controlado con Losartán (Cozaar).');
-- Paciente 7 (Gabriel) tiene Hipertensión y Diabetes
INSERT INTO FIDE_PACIENTE_ENFERMEDAD_TB (ID_PACIENTE, ID_ENFERMEDAD, FECHA_DIAGNOSTICO, NOTAS)
VALUES (7, 1, TO_DATE('2010-06-20', 'YYYY-MM-DD'), 'Paciente con monitoreo estricto.');
INSERT INTO FIDE_PACIENTE_ENFERMEDAD_TB (ID_PACIENTE, ID_ENFERMEDAD, FECHA_DIAGNOSTICO, NOTAS)
VALUES (7, 2, TO_DATE('2012-01-15', 'YYYY-MM-DD'), 'Controlado con Metformina.');
-- Paciente 8 (Hilda) tiene Asma
INSERT INTO FIDE_PACIENTE_ENFERMEDAD_TB (ID_PACIENTE, ID_ENFERMEDAD, FECHA_DIAGNOSTICO, NOTAS)
VALUES (8, 3, TO_DATE('1980-11-01', 'YYYY-MM-DD'), 'Asma crónica desde la juventud, usa inhalador.');

COMMIT;

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: INSERTS PARA EL BLOQUE 5 (INVENTARIOS Y CITAS)
-- REGLA: Cada sucursal debe tener al menos 5 medicamentos en inventario.
*/

-- 16. FIDE_INVENTARIO_TB (Stock de medicamentos por sucursal)
-- Sede Sabana (ID_SUCURSAL = 1)
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (1, 1, 1, 500, TO_DATE('2027-12-31', 'YYYY-MM-DD'), 1); -- Tylenol
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (2, 1, 3, 250, TO_DATE('2026-10-31', 'YYYY-MM-DD'), 1); -- Amoxil
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (3, 1, 8, 300, TO_DATE('2027-05-30', 'YYYY-MM-DD'), 1); -- Lipitor
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (4, 1, 2, 400, TO_DATE('2027-08-31', 'YYYY-MM-DD'), 1); -- Advil
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (5, 1, 4, 200, TO_DATE('2028-01-31', 'YYYY-MM-DD'), 1); -- Cozaar

-- Sede San Pedro (ID_SUCURSAL = 2)
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (6, 2, 2, 400, TO_DATE('2027-08-31', 'YYYY-MM-DD'), 1); -- Advil
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (7, 2, 6, 150, TO_DATE('2026-11-30', 'YYYY-MM-DD'), 1); -- Ventolin
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (8, 2, 1, 300, TO_DATE('2027-12-31', 'YYYY-MM-DD'), 1); -- Tylenol
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (9, 2, 3, 200, TO_DATE('2026-10-31', 'YYYY-MM-DD'), 1); -- Amoxil
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (10, 2, 5, 100, TO_DATE('2027-07-31', 'YYYY-MM-DD'), 1); -- Glucophage (Metformina)

-- Sede Alajuela (ID_SUCURSAL = 3)
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (11, 3, 1, 300, TO_DATE('2027-12-31', 'YYYY-MM-DD'), 1); -- Tylenol
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (12, 3, 4, 200, TO_DATE('2028-01-31', 'YYYY-MM-DD'), 1); -- Cozaar
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (13, 3, 2, 250, TO_DATE('2027-08-31', 'YYYY-MM-DD'), 1); -- Advil
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (14, 3, 5, 150, TO_DATE('2027-07-31', 'YYYY-MM-DD'), 1); -- Glucophage (Metformina)
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (15, 3, 8, 100, TO_DATE('2027-05-30', 'YYYY-MM-DD'), 1); -- Lipitor

-- Sede Heredia (ID_SUCURSAL = 4)
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (16, 4, 7, 100, TO_DATE('2027-09-30', 'YYYY-MM-DD'), 1); -- Eutirox
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (17, 4, 1, 400, TO_DATE('2027-12-31', 'YYYY-MM-DD'), 1); -- Tylenol
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (18, 4, 6, 150, TO_DATE('2026-11-30', 'YYYY-MM-DD'), 1); -- Ventolin
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (19, 4, 3, 200, TO_DATE('2026-10-31', 'YYYY-MM-DD'), 1); -- Amoxil
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (20, 4, 2, 300, TO_DATE('2027-08-31', 'YYYY-MM-DD'), 1); -- Advil

-- 17. FIDE_CITA_TB (Agendamiento de citas - Sin cambios)
-- Citas Completadas (Estado 4) - Listas para historial y facturación
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (1, 1, 3, 1, TO_TIMESTAMP('2025-11-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Consulta general, chequeo anual.', 4);
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (2, 2, 4, 1, TO_TIMESTAMP('2025-11-11 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Revisión cardiológica, dolor de pecho leve.', 4);
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (3, 4, 10, 3, TO_TIMESTAMP('2025-11-12 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Control de hipertensión y receta.', 4);
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (4, 7, 10, 3, TO_TIMESTAMP('2025-11-12 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Control de diabetes y presión alta.', 4);
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (5, 8, 7, 2, TO_TIMESTAMP('2025-11-13 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Dificultad para respirar, revisión de asma.', 4);

-- Citas Pendientes (Estado 3) - Para el futuro
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (6, 3, 12, 4, TO_TIMESTAMP('2025-11-20 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Revisión de lunares, dermatología.', 3);
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (7, 5, 3, 1, TO_TIMESTAMP('2025-11-21 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Gripe fuerte, 3 días de fiebre.', 3);

-- Cita Anulada (Estado 5)
INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
VALUES (8, 6, 7, 2, TO_TIMESTAMP('2025-11-14 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Paciente canceló, reprogramará.', 5);

COMMIT;

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: INSERTS PARA EL BLOQUE 6 (HISTORIAL Y FACTURACION)
-- Se generan registros para las 5 citas completadas (ID_CITA 1-5) del Bloque 5.
-- IDs de referencia usados:
-- FIDE_CITA_TB: 1, 2, 3, 4, 5 (Completadas)
-- FIDE_INVENTARIO_TB: IDs de inventario (1-20)
-- FIDE_ESTADO_TB: 1 (Activo - para Factura)
*/

-- 18. FIDE_HISTORIAL_CLINICO_TB (Diagnóstico de las citas completadas)
INSERT INTO FIDE_HISTORIAL_CLINICO_TB (ID_HISTORIAL, ID_CITA, DIAGNOSTICO, PROCEDIMIENTOS_REALIZADOS, TRATAMIENTO_SUGERIDO)
VALUES (1, 1, 'Chequeo general sin hallazgos patológicos.', 'Toma de presión arterial (120/80), examen de sangre de rutina.', 'Mantener dieta saludable y ejercicio regular. Próximo chequeo en 1 año.');
INSERT INTO FIDE_HISTORIAL_CLINICO_TB (ID_HISTORIAL, ID_CITA, DIAGNOSTICO, PROCEDIMIENTOS_REALIZADOS, TRATAMIENTO_SUGERIDO)
VALUES (2, 2, 'Angina de pecho estable (sospecha).', 'Electrocardiograma (EKG) en reposo.', 'Se refiere para prueba de esfuerzo. Se receta Atorvastatina (Lipitor) para control de colesterol.');
INSERT INTO FIDE_HISTORIAL_CLINICO_TB (ID_HISTORIAL, ID_CITA, DIAGNOSTICO, PROCEDIMIENTOS_REALIZADOS, TRATAMIENTO_SUGERIDO)
VALUES (3, 3, 'Hipertensión Arterial Grado 1 (Control).', 'Revisión de bitácora de presión arterial, ajuste de dosis.', 'Continuar con Losartán (Cozaar). Nueva receta por 3 meses.');
INSERT INTO FIDE_HISTORIAL_CLINICO_TB (ID_HISTORIAL, ID_CITA, DIAGNOSTICO, PROCEDIMIENTOS_REALIZADOS, TRATAMIENTO_SUGERIDO)
VALUES (4, 4, 'Diabetes Mellitus Tipo 2 y HTA (Control).', 'Examen de Hemoglobina Glicosilada (HbA1c), revisión de pies.', 'Continuar con Metformina (Glucophage) y Losartán. Se añade Atorvastatina (Lipitor) como preventivo.');
INSERT INTO FIDE_HISTORIAL_CLINICO_TB (ID_HISTORIAL, ID_CITA, DIAGNOSTICO, PROCEDIMIENTOS_REALIZADOS, TRATAMIENTO_SUGERIDO)
VALUES (5, 5, 'Crisis asmática leve.', 'Nebulización en consultorio, medición de oximetría.', 'Se receta inhalador de Salbutamol (Ventolin) para crisis. Se sugiere cita de seguimiento.');

-- 19. FIDE_FACTURA_TB (Cabecera de las facturas)
-- Cita 1 (Chequeo)
INSERT INTO FIDE_FACTURA_TB (ID_FACTURA, ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, DESCUENTO_PORCENTAJE, MONTO_TOTAL, ID_ESTADO)
VALUES (1, 1, TO_DATE('2025-11-10', 'YYYY-MM-DD'), 40000.00, 5200.00, 0, 45200.00, 1);
-- Cita 2 (Cardiología)
INSERT INTO FIDE_FACTURA_TB (ID_FACTURA, ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, DESCUENTO_PORCENTAJE, MONTO_TOTAL, ID_ESTADO)
VALUES (2, 2, TO_DATE('2025-11-11', 'YYYY-MM-DD'), 110000.00, 14300.00, 0, 124300.00, 1);
-- Cita 3 (Control HTA)
INSERT INTO FIDE_FACTURA_TB (ID_FACTURA, ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, DESCUENTO_PORCENTAJE, MONTO_TOTAL, ID_ESTADO)
VALUES (3, 3, TO_DATE('2025-11-12', 'YYYY-MM-DD'), 55000.00, 7150.00, 0, 62150.00, 1);
-- Cita 4 (Control Diabetes)
INSERT INTO FIDE_FACTURA_TB (ID_FACTURA, ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, DESCUENTO_PORCENTAJE, MONTO_TOTAL, ID_ESTADO)
VALUES (4, 4, TO_DATE('2025-11-12', 'YYYY-MM-DD'), 135000.00, 17550.00, 0, 152550.00, 1);
-- Cita 5 (Asma)
INSERT INTO FIDE_FACTURA_TB (ID_FACTURA, ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, DESCUENTO_PORCENTAJE, MONTO_TOTAL, ID_ESTADO)
VALUES (5, 5, TO_DATE('2025-11-13', 'YYYY-MM-DD'), 70000.00, 9100.00, 0, 79100.00, 1);

-- 20. FIDE_FACTURA_DETALLE_TB (Detalle de las facturas)
-- Factura 1 (ID_FACTURA = 1)
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (1, 1, 'Consulta Medicina General', NULL, 1, 40000.00, 40000.00);

-- Factura 2 (ID_FACTURA = 2) - Múltiples líneas
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (2, 2, 'Consulta Cardiología', NULL, 1, 60000.00, 60000.00);
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (3, 2, 'Electrocardiograma (EKG)', NULL, 1, 35000.00, 35000.00);
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (4, 2, 'Lipitor 20mg (ID_INV: 3)', 3, 1, 15000.00, 15000.00); -- Venta de Medicamento (Sede 1)

-- Factura 3 (ID_FACTURA = 3)
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (5, 3, 'Consulta Medicina General', NULL, 1, 40000.00, 40000.00);
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (6, 3, 'Cozaar 50mg (ID_INV: 12)', 12, 1, 15000.00, 15000.00);

-- Factura 4 (ID_FACTURA = 4)
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (7, 4, 'Consulta Medicina General', NULL, 1, 40000.00, 40000.00);
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (8, 4, 'Examen HbA1c (Laboratorio)', NULL, 1, 20000.00, 20000.00);
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (9, 4, 'Glucophage 850mg (ID_INV: 14)', 14, 2, 10000.00, 20000.00); -- Venta (Sede 3)
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (10, 4, 'Lipitor 20mg (ID_INV: 15)', 15, 1, 15000.00, 15000.00); -- Venta (Sede 3)
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (11, 4, 'Cozaar 50mg (ID_INV: 12)', 12, 1, 15000.00, 15000.00); -- Venta (Sede 3)
-- (La cita 4 fue en Sede 3, así que los ID_INV 12, 14, 15 son correctos)

-- Factura 5 (ID_FACTURA = 5)
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (12, 5, 'Consulta Medicina General', NULL, 1, 40000.00, 40000.00);
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (13, 5, 'Nebulización (Procedimiento)', NULL, 1, 20000.00, 20000.00);
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES (14, 5, 'Ventolin Inhalador (ID_INV: 7)', 7, 1, 10000.00, 10000.00); -- Venta (Sede 2)
-- (La cita 5 fue en Sede 2, el ID_INV 7 (Ventolin) es correcto)

COMMIT;

-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- DESCRIPCION: GENERADOR DE PACIENTES ADICIONALES (IDs 9 al 30)
SET SERVEROUTPUT ON;
DECLARE
    TYPE t_nombres IS TABLE OF VARCHAR2(50);
    v_nombres t_nombres := t_nombres('Jorge', 'Marta', 'Luis', 'Patricia', 'Ricardo', 'Teresa', 'Oscar', 'Lorena', 'Sergio', 'Claudia', 'Victor', 'Monica');
    v_apellidos t_nombres := t_nombres('Vargas', 'Castillo', 'Romero', 'Mendez', 'Guzman', 'Navarro', 'Salazar', 'Aguilar', 'Delgado', 'Cordero', 'Rivera', 'Solis');
    
    v_nombre_completo VARCHAR2(30);
    v_apellido1 VARCHAR2(30);
    v_apellido2 VARCHAR2(30);
    v_direccion_id NUMBER;
BEGIN
    FOR i IN 9..30 LOOP
        -- Selección aleatoria de nombres y apellidos
        v_nombre_completo := v_nombres(TRUNC(DBMS_RANDOM.VALUE(1, v_nombres.COUNT + 1)));
        v_apellido1 := v_apellidos(TRUNC(DBMS_RANDOM.VALUE(1, v_apellidos.COUNT + 1)));
        v_apellido2 := v_apellidos(TRUNC(DBMS_RANDOM.VALUE(1, v_apellidos.COUNT + 1)));
        v_direccion_id := TRUNC(DBMS_RANDOM.VALUE(1, 10)); -- Direcciones 1-10
        
        INSERT INTO FIDE_PACIENTE_TB (ID_PACIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO) 
        VALUES (i, v_nombre_completo, v_apellido1, v_apellido2, TO_DATE('1970-01-01','YYYY-MM-DD') + TRUNC(DBMS_RANDOM.VALUE(0, 15000)), v_direccion_id, 1);
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Se han creado 22 pacientes nuevos.');
END;
/

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- DESCRIPCION: AMPLIACIÓN DE CATALOGO DE MEDICAMENTOS E INVENTARIO
-- OBJETIVO: Mejorar la visualización en la Web App con más variedad de datos.
*/

-- A. NUEVOS MEDICAMENTOS EN EL CATÁLOGO (IDs 9 al 15)
INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) 
VALUES (9, 'Aspirina Protect', 'Ácido Acetilsalicílico', 'Tableta 81mg');

INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) 
VALUES (10, 'Omeprazol Genfar', 'Omeprazol', 'Cápsula 20mg');

INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) 
VALUES (11, 'Voltaren', 'Diclofenaco Sódico', 'Inyectable 75mg');

INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) 
VALUES (12, 'Allegra', 'Fexofenadina', 'Tableta 120mg');

INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) 
VALUES (13, 'Lantus SoloStar', 'Insulina Glargina', 'Pluma inyectable 3ml');

INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) 
VALUES (14, 'Zyloprim', 'Alopurinol', 'Tableta 300mg');

INSERT INTO FIDE_MEDICAMENTO_TB (ID_MEDICAMENTO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION) 
VALUES (15, 'Plasil', 'Metoclopramida', 'Solución Oral 100ml');


-- B. ASIGNACIÓN DE STOCK A SUCURSALES (IDs Inventario 21 al 35)
-- Nota: Distribuimos los nuevos medicamentos de forma variada entre las 4 sedes.

-- Sede Sabana (ID 1) - Agregamos Aspirina, Omeprazol, Voltaren
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (21, 1, 9, 600, TO_DATE('2028-01-01', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (22, 1, 10, 350, TO_DATE('2027-06-15', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (23, 1, 11, 100, TO_DATE('2026-12-31', 'YYYY-MM-DD'), 1);

-- Sede San Pedro (ID 2) - Agregamos Allegra, Lantus, Aspirina
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (24, 2, 12, 200, TO_DATE('2027-09-20', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (25, 2, 13, 50, TO_DATE('2026-08-10', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (26, 2, 9, 450, TO_DATE('2028-02-28', 'YYYY-MM-DD'), 1);

-- Sede Alajuela (ID 3) - Agregamos Zyloprim, Plasil, Omeprazol, Voltaren
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (27, 3, 14, 150, TO_DATE('2027-11-11', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (28, 3, 15, 80, TO_DATE('2026-05-05', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (29, 3, 10, 300, TO_DATE('2027-07-20', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (30, 3, 11, 120, TO_DATE('2026-11-30', 'YYYY-MM-DD'), 1);

-- Sede Heredia (ID 4) - Agregamos Allegra, Lantus, Zyloprim, Aspirina
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (31, 4, 12, 180, TO_DATE('2027-10-15', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (32, 4, 13, 60, TO_DATE('2026-09-01', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (33, 4, 14, 140, TO_DATE('2027-12-01', 'YYYY-MM-DD'), 1);
INSERT INTO FIDE_INVENTARIO_TB (ID_INVENTARIO, ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO) 
VALUES (34, 4, 9, 500, TO_DATE('2028-03-15', 'YYYY-MM-DD'), 1);

COMMIT;

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: BLOQUE PL/SQL Generacion de 145 facturas
*/
SET SERVEROUTPUT ON;
DECLARE
    -- IDs de control
    v_paciente_id NUMBER;
    v_medico_id NUMBER;
    v_sucursal_id NUMBER;
    v_inventario_id NUMBER;
    v_detalle_id NUMBER := 15; -- Continuamos desde el último ID manual (14)
    v_fecha_cita TIMESTAMP;
    v_fecha_emision DATE;
    
    -- Variables temporales de texto
    v_motivo_actual VARCHAR2(300);
    v_diagnostico_actual VARCHAR2(300);
    v_tratamiento_actual VARCHAR2(300);
    
    -- Variables lógicas y de calculo
    v_incluir_medicamento BOOLEAN;
    v_precio_consulta DECIMAL(9,2) := 45000;
    v_precio_medicamento DECIMAL(9,2);
    v_subtotal_factura DECIMAL(12,2);
    v_iva DECIMAL(12,2);
    v_total_factura NUMBER(9,2);

    -- Listas de datos (Tipos)
    TYPE t_lista_varchar IS TABLE OF VARCHAR2(300);
    
    v_motivos t_lista_varchar := t_lista_varchar(
        'Dolor de cabeza crónico', 'Revisión de gripe', 'Control de presión arterial', 
        'Seguimiento de diabetes', 'Dolor de espalda bajo', 'Revisión de alergia estacional',
        'Chequeo general', 'Certificado médico', 'Examen de sangre de rutina', 
        'Molestia estomacal', 'Chequeo de lunares', 'Fatiga constante'
    );
    
    v_diagnosticos t_lista_varchar := t_lista_varchar(
        'Migraña tensional', 'Infección viral (gripe común)', 'Hipertensión Arterial controlada',
        'Diabetes Mellitus Tipo 2 estable', 'Lumbalgia mecánica', 'Rinitis alérgica',
        'Paciente saludable', 'Faringitis aguda', 'Vértigo posicional',
        'Gastritis leve', 'Dermatitis de contacto', 'Anemia leve'
    );
    
    v_tratamientos t_lista_varchar := t_lista_varchar(
        'Reposo y Acetaminofén', 'Ibuprofeno 400mg cada 8 horas', 
        'Continuar tratamiento actual', 'Ajuste de dosis de Metformina',
        'Fisioterapia y analgésicos', 'Loratadina 10mg al día', 'Mantener estilo de vida saludable',
        'Amoxicilina 500mg cada 8 horas', 'Maniobras de Epley',
        'Omeprazol en ayunas', 'Crema tópica y evitar sol', 'Suplementos de hierro'
    );
    
BEGIN
    DBMS_OUTPUT.PUT_LINE('Iniciando la generación masiva de transacciones...');
    
    FOR v_id IN 6..150 LOOP
        -- 1. SELECCIONAR DATOS BASE
        v_paciente_id := TRUNC(DBMS_RANDOM.VALUE(1, 31)); -- 30 Pacientes
        v_sucursal_id := TRUNC(DBMS_RANDOM.VALUE(1, 5));  -- Sucursales 1 al 4
        v_fecha_cita := TO_TIMESTAMP('2025-09-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS') + DBMS_RANDOM.VALUE(1, 60);
        v_fecha_emision := TRUNC(v_fecha_cita);

        -- Seleccionar Médico
        SELECT ID_PERSONAL INTO v_medico_id
        FROM FIDE_PERSONAL_TB
        WHERE ID_SUCURSAL = v_sucursal_id AND ID_ROL_PERSONAL IN (1, 2)
        ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY;

        -- Variables de texto
        v_motivo_actual := v_motivos(TRUNC(DBMS_RANDOM.VALUE(1, v_motivos.COUNT + 1)));
        v_diagnostico_actual := v_diagnosticos(TRUNC(DBMS_RANDOM.VALUE(1, v_diagnosticos.COUNT + 1)));
        v_tratamiento_actual := v_tratamientos(TRUNC(DBMS_RANDOM.VALUE(1, v_tratamientos.COUNT + 1)));

        -- 2. INSERTAR CITA Y HISTORIAL
        INSERT INTO FIDE_CITA_TB (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_SUCURSAL, FECHA_HORA_CITA, MOTIVA_CONSULTA, ID_ESTADO)
        VALUES (v_id, v_paciente_id, v_medico_id, v_sucursal_id, v_fecha_cita, v_motivo_actual, 4);
        
        INSERT INTO FIDE_HISTORIAL_CLINICO_TB (ID_HISTORIAL, ID_CITA, DIAGNOSTICO, PROCEDIMIENTOS_REALIZADOS, TRATAMIENTO_SUGERIDO)
        VALUES (v_id, v_id, v_diagnostico_actual, 'Evaluación médica completa.', v_tratamiento_actual);
        
        -- 3. CALCULAR MONTOS (EN MEMORIA) ANTES DE INSERTAR
        v_subtotal_factura := v_precio_consulta;
        v_incluir_medicamento := FALSE;
        v_inventario_id := NULL; 

        -- Lógica de Medicina (60% prob)
        IF DBMS_RANDOM.VALUE(0, 1) > 0.4 THEN
            BEGIN
                SELECT ID_INVENTARIO, TRUNC(DBMS_RANDOM.VALUE(5000, 25000)) 
                INTO v_inventario_id, v_precio_medicamento
                FROM FIDE_INVENTARIO_TB
                WHERE ID_SUCURSAL = v_sucursal_id
                ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY;
                
                -- Sumar al subtotal en memoria
                v_subtotal_factura := v_subtotal_factura + v_precio_medicamento;
                v_incluir_medicamento := TRUE;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN NULL; 
            END;
        END IF;

        -- Calcular totales finales
        v_iva := v_subtotal_factura * 0.13;
        v_total_factura := v_subtotal_factura + v_iva;
        
        -- 4. INSERTAR FACTURA (PADRE) - AHORA SÍ VA PRIMERO
        INSERT INTO FIDE_FACTURA_TB (ID_FACTURA, ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, DESCUENTO_PORCENTAJE, MONTO_TOTAL, ID_ESTADO)
        VALUES (v_id, v_id, v_fecha_emision, v_subtotal_factura, v_iva, 0, v_total_factura, 1);
        
        -- 5. INSERTAR DETALLES (HIJOS) - AHORA SÍ VA DESPUÉS
        -- Detalle 1: Consulta
        INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
        VALUES (v_detalle_id, v_id, 'Consulta Médica General', NULL, 1, v_precio_consulta, v_precio_consulta);
        v_detalle_id := v_detalle_id + 1; 

        -- Detalle 2: Medicina (Si aplica)
        IF v_incluir_medicamento THEN
            INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_DETALLE, ID_FACTURA, CONCEPTO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
            VALUES (v_detalle_id, v_id, 'Farmacia', v_inventario_id, 1, v_precio_medicamento, v_precio_medicamento);
            v_detalle_id := v_detalle_id + 1; 
        END IF;
        
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('¡Éxito! Se generaron 145 facturas sin errores de integridad.');
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error crítico: ' || SQLERRM);
        ROLLBACK;
END;
/

BEGIN
    DELETE FROM FIDE_FACTURA_DETALLE_TB WHERE ID_FACTURA >= 6;
    DELETE FROM FIDE_FACTURA_TB WHERE ID_CITA >= 6;
    DELETE FROM FIDE_HISTORIAL_CLINICO_TB WHERE ID_CITA >= 6;
    DELETE FROM FIDE_CITA_TB WHERE ID_CITA >= 6;
    COMMIT;
END;
/

/*
-- PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL" 
-- FECHA DE CREACION: 16/11/25 
-- DESCRIPCION: INSERTS PARA EL BLOQUE 7 (SEGURIDAD Y USUARIOS)
-- IDs de referencia:
-- Roles Sistema: 1 (Admin), 2 (Médico), 3 (Recepción), 4 (Paciente)
*/

-- 1. USUARIOS ADMINISTRATIVOS Y DE SOPORTE
-- Carlos Mora (Admin de Sede 1)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (1, 'cmora', 'admin123', 1, NULL, 1, 1);

-- 2. USUARIOS DEL PERSONAL MÉDICO (Doctores y Enfermeros)
-- Dr. Miguel Arias (Sede 1)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (2, 'marias', 'doc123', 3, NULL, 2, 1);

-- Dra. Elena Rojas (Cardióloga Sede 1)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (3, 'erojas', 'doc123', 4, NULL, 2, 1);

-- Dr. Andrés Vega (Sede 2)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (4, 'avega', 'doc123', 7, NULL, 2, 1);

-- Dra. Ana Hernández (Sede 3)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (5, 'ahernandez', 'doc123', 10, NULL, 2, 1);

-- Dr. Luis Ramírez (Dermatólogo Sede 4)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (6, 'lramirez', 'doc123', 12, NULL, 2, 1);

-- 3. USUARIOS DE RECEPCIÓN (Para agendar citas)
-- Lucía Fernández (Recepción Sede 1)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (7, 'lfernandez', 'recep123', 2, NULL, 3, 1);

-- Sofía Jiménez (Recepción Sede 2)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (8, 'sjimenez', 'recep123', 6, NULL, 3, 1);

-- 4. USUARIOS PACIENTES (Para portal de autogestión)
-- Ana Soto (Paciente 1)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (9, 'asoto', 'paciente123', NULL, 1, 4, 1);

-- Bruno Díaz (Paciente 2)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (10, 'bdiaz', 'batman123', NULL, 2, 4, 1);

-- Carla Vega (Paciente 3)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (11, 'cvega', 'paciente123', NULL, 3, 4, 1);

-- Gabriel Jiménez (Paciente 7)
INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
VALUES (12, 'gjimenez', 'paciente123', NULL, 7, 4, 1);

COMMIT;

