/* PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL"          
FECHA DE CREACION: 17/11/25 
DESCRIPCION: CREACION DE LAS VISTAS
*/

CREATE OR REPLACE VIEW FIDE_RESUMEN_VENTAS_SUCURSAL_V AS
SELECT 
    S.NOMBRE AS NOMBRE_SUCURSAL,
    COUNT(F.ID_FACTURA) AS "CANTIDAD FACTURAS",
    SUM(F.SUBTOTAL) AS SUBTOTAL_ACUMULADO,
    SUM(F.IVA) AS IVA_ACUMULADO,
    SUM(F.MONTO_TOTAL) AS TOTAL_GENERAL
FROM FIDE_SUCURSAL_TB S
JOIN FIDE_CITA_TB C ON S.ID_SUCURSAL = C.ID_SUCURSAL
JOIN FIDE_FACTURA_TB F ON C.ID_CITA = F.ID_CITA
WHERE F.ID_ESTADO = 1 -- Solo facturas activas
GROUP BY S.NOMBRE;
----------------
SELECT * FROM FIDE_RESUMEN_VENTAS_SUCURSAL_V;
----------------
/

CREATE OR REPLACE VIEW FIDE_DIRECTORIO_PERSONAL_V AS
SELECT 
    P.ID_PERSONAL,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO AS NOMBRE_COMPLETO,
    R.NOMBRE_ROL AS PUESTO,
    S.NOMBRE AS "SEDE ASIGNADA",
    P.FECHA_CONTRATACION,
    CASE 
        WHEN P.ID_ESTADO = 1 THEN 'Activo'
        ELSE 'Inactivo'
    END AS ESTADO_ACTUAL
FROM FIDE_PERSONAL_TB P
JOIN FIDE_ROL_PERSONAL_TB R ON P.ID_ROL_PERSONAL = R.ID_ROL_PERSONAL
JOIN FIDE_SUCURSAL_TB S ON P.ID_SUCURSAL = S.ID_SUCURSAL;
----------------
SELECT * FROM FIDE_DIRECTORIO_PERSONAL_V;
----------------

CREATE OR REPLACE VIEW FIDE_PACIENTES_CON_ALERGIAS_V
 AS
SELECT
    P.NOMBRE|| ' ' ||APELLIDO_PATERNO|| ' ' ||APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    A.NOMBRE_ALERGIA,
    PA.NOTAS AS NOTA
FROM
    FIDE_PACIENTE_TB P, FIDE_PACIENTE_ALERGIA_TB PA, FIDE_ALERGIA_TB A
WHERE
    P.ID_PACIENTE = PA.ID_PACIENTE
AND 
    PA.ID_ALERGIA =  A.ID_ALERGIA;
/   
----------------
SELECT * FROM FIDE_PACIENTES_CON_ALERGIAS_V;
----------------

--- VER PACIENTES CON ENFERMEDADES ---
CREATE OR REPLACE VIEW FIDE_PACIENTES_CON_ENFERMEDADES_V AS
SELECT
    P.NOMBRE|| ' ' ||APELLIDO_PATERNO|| ' ' ||APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    A.NOMBRE_ENFERMEDAD,
    PA.NOTAS AS NOTA
FROM
    FIDE_PACIENTE_TB P, FIDE_PACIENTE_ENFERMEDAD_TB PA, FIDE_ENFERMEDAD_CRONICA_TB A
WHERE
    P.ID_PACIENTE = PA.ID_PACIENTE
AND 
    PA.ID_ENFERMEDAD =  A.ID_ENFERMEDAD;
/
----------------
SELECT * FROM FIDE_PACIENTES_CON_ENFERMEDADES_V;
----------------

---  PACIENTES CON CITAS ---
CREATE OR REPLACE VIEW FIDE_PACIENTES_CON_CITAS_V AS
SELECT
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    C.FECHA_HORA_CITA,
    PE.NOMBRE || ' ' || PE.APELLIDO_PATERNO || ' ' || PE.APELLIDO_MATERNO AS NOMBRE_MEDICO
FROM
    FIDE_PACIENTE_TB P, FIDE_CITA_TB C, FIDE_PERSONAL_TB PE
WHERE
     C.ID_PACIENTE = P.ID_PACIENTE
AND 
    C.ID_MEDICO = PE.ID_PERSONAL;
/
----------------
SELECT * FROM FIDE_PACIENTES_CON_CITAS_V;
