---ALTERS

ALTER TABLE FIDE_ALERGIA_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_CANTONES_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_CITA_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_DIRECCIONES_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_DISTRITOS_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_ENFERMEDAD_CRONICA_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_ESTADO_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_FACTURA_DETALLE_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_FACTURA_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_HISTORIAL_CLINICO_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_INVENTARIO_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_MEDICAMENTO_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_PACIENTE_ALERGIA_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_PACIENTE_ENFERMEDAD_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_PACIENTE_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_PERSONAL_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_PROVINCIAS_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_ROL_PERSONAL_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_ROL_SISTEMA_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_SUCURSAL_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_USUARIO_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_SERVICIO_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);

ALTER TABLE FIDE_CARRITO_TB
ADD(
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
ACCION VARCHAR(100)
);