--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body FIDE_SALUDTOTAL_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "FIDE_SALUDTOTAL_BD"."FIDE_SALUDTOTAL_PKG" AS 

PROCEDURE FIDE_ALERGIA_INSERT_SP(
P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_NOMBRE_ALERGIA IN FIDE_ALERGIA_TB.NOMBRE_ALERGIA%TYPE
)IS
BEGIN
    INSERT INTO FIDE_ALERGIA_TB(NOMBRE_ALERGIA)
    VALUES (P_NOMBRE_ALERGIA);
    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_CITA_DELETE_SP(
P_ID_CITA IN FIDE_CITA_TB.ID_CITA%TYPE,
P_ID_PACIENTE IN FIDE_CITA_TB.ID_PACIENTE%TYPE,
P_ID_MEDICO IN FIDE_CITA_TB.ID_MEDICO%TYPE,
P_ID_SUCURSAL IN FIDE_CITA_TB.ID_SUCURSAL%TYPE,
P_FECHA_HORA_CITA IN FIDE_CITA_TB.FECHA_HORA_CITA%TYPE,
P_MOTIVA_CONSULTA IN FIDE_CITA_TB.MOTIVA_CONSULTA%TYPE,
P_ID_ESTADO IN FIDE_CITA_TB.ID_ESTADO%TYPE
)IS 
BEGIN
    UPDATE FIDE_CITA_TB
    SET 
        ID_PACIENTE = P_ID_PACIENTE,
        ID_MEDICO = P_ID_MEDICO,
        ID_SUCURSAL = P_ID_SUCURSAL,
        FECHA_HORA_CITA = P_FECHA_HORA_CITA,
        MOTIVA_CONSULTA = P_MOTIVA_CONSULTA,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_CITA = P_ID_CITA;
    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_CITA_INSERT_SP(
P_ID_CITA IN FIDE_CITA_TB.ID_CITA%TYPE,
P_ID_PACIENTE IN FIDE_CITA_TB.ID_PACIENTE%TYPE,
P_ID_MEDICO IN FIDE_CITA_TB.ID_MEDICO%TYPE,
P_ID_SUCURSAL IN FIDE_CITA_TB.ID_SUCURSAL%TYPE,
P_FECHA_HORA_CITA IN FIDE_CITA_TB.FECHA_HORA_CITA%TYPE,
P_MOTIVA_CONSULTA IN FIDE_CITA_TB.MOTIVA_CONSULTA%TYPE,
P_ID_ESTADO IN FIDE_CITA_TB.ID_ESTADO%TYPE
)IS
BEGIN
    INSERT INTO FIDE_CITA_TB(ID_PACIENTE,ID_MEDICO,ID_SUCURSAL,FECHA_HORA_CITA,MOTIVA_CONSULTA,ID_ESTADO)
    VALUES (P_ID_PACIENTE,P_ID_MEDICO,P_ID_SUCURSAL,P_FECHA_HORA_CITA,P_MOTIVA_CONSULTA,P_ID_ESTADO);
    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_ENFERMEDAD_CRONICA_INSERT_SP(
P_ID_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.ID_ENFERMEDAD%TYPE,
P_NOMBRE_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.NOMBRE_ENFERMEDAD%TYPE
)IS
BEGIN
    INSERT INTO FIDE_ENFERMEDAD_CRONICA_TB(NOMBRE_ENFERMEDAD)
    VALUES (P_NOMBRE_ENFERMEDAD);
    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_HISTORIAL_CLINICO_INSERT_SP(
P_ID_HISTORIAL IN FIDE_HISTORIAL_CLINICO_TB.ID_HISTORIAL%TYPE,
P_ID_CITA IN FIDE_HISTORIAL_CLINICO_TB.ID_CITA%TYPE,
P_DIAGNOSTICO IN FIDE_HISTORIAL_CLINICO_TB.DIAGNOSTICO%TYPE,
P_PROCEDIMIENTOS_REALIZADOS IN FIDE_HISTORIAL_CLINICO_TB.PROCEDIMIENTOS_REALIZADOS%TYPE,
P_TRATAMIENTO_SUGERIDO IN FIDE_HISTORIAL_CLINICO_TB.TRATAMIENTO_SUGERIDO%TYPE
)IS 
BEGIN
    INSERT INTO FIDE_HISTORIAL_CLINICO_TB(ID_CITA,DIAGNOSTICO,PROCEDIMIENTOS_REALIZADOS,TRATAMIENTO_SUGERIDO)
    VALUES(P_ID_CITA,P_DIAGNOSTICO,P_PROCEDIMIENTOS_REALIZADOS,P_TRATAMIENTO_SUGERIDO);
    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_PACIENTE_ALERGIA_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ALERGIA_TB.ID_PACIENTE%TYPE,
P_ID_ALERGIA IN FIDE_PACIENTE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ALERGIA_TB.FECHA_DIAGNOSTICO%TYPE,
P_NIVEL_SEVERIDAD IN FIDE_PACIENTE_ALERGIA_TB.NIVEL_SEVERIDAD%TYPE,
P_NOTAS IN FIDE_PACIENTE_ALERGIA_TB.NOTAS%TYPE
) IS 
BEGIN
    INSERT INTO FIDE_PACIENTE_ALERGIA_TB(ID_ALERGIA,FECHA_DIAGNOSTICO,NIVEL_SEVERIDAD,NOTAS)
    VALUES (P_ID_ALERGIA,P_FECHA_DIAGNOSTICO,P_NIVEL_SEVERIDAD,P_NOTAS);
    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_PACIENTE_DELETE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE
) IS
BEGIN
    UPDATE FIDE_PACIENTE_TB
    SET ID_ESTADO = 2
    WHERE ID_PACIENTE = P_ID_PACIENTE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_PACIENTE_ENFERMEDAD_INSERT_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_PACIENTE%TYPE,
P_ID_ENFERMEDAD IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_ENFERMEDAD%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ENFERMEDAD_TB.FECHA_DIAGNOSTICO%TYPE,
P_NOTAS IN FIDE_PACIENTE_ENFERMEDAD_TB.NOTAS%TYPE
)IS
BEGIN
    INSERT INTO FIDE_PACIENTE_ENFERMEDAD_TB(ID_PACIENTE,ID_ENFERMEDAD,FECHA_DIAGNOSTICO,NOTAS)
    VALUES (P_ID_PACIENTE,P_ID_ENFERMEDAD,P_FECHA_DIAGNOSTICO,P_NOTAS);
    COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_CITA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_CITA_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;

PROCEDURE FIDE_PACIENTE_ENFERMEDAD_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PACIENTE_ENFERMEDAD_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;

PROCEDURE FIDE_PACIENTE_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PACIENTE_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;

PROCEDURE FIDE_PACIENTE_ALERGIA_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ALERGIA_TB.ID_PACIENTE%TYPE,
P_ID_ALERGIA IN FIDE_PACIENTE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ALERGIA_TB.FECHA_DIAGNOSTICO%TYPE,
P_NIVEL_SEVERIDAD IN FIDE_PACIENTE_ALERGIA_TB.NIVEL_SEVERIDAD%TYPE,
P_NOTAS IN FIDE_PACIENTE_ALERGIA_TB.NOTAS%TYPE
)IS
BEGIN
    UPDATE FIDE_PACIENTE_ALERGIA_TB
    SET 
        ID_PACIENTE = P_ID_PACIENTE,
        ID_ALERGIA = P_ID_ALERGIA,
        FECHA_DIAGNOSTICO = P_FECHA_DIAGNOSTICO,
        NIVEL_SEVERIDAD = P_NIVEL_SEVERIDAD,
        NOTAS = P_NOTAS
    WHERE ID_PACIENTE = P_ID_PACIENTE;
    COMMIT;
END;

PROCEDURE FIDE_HISTORIAL_CLINICO_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_HISTORIAL_CLINICO_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;

PROCEDURE FIDE_HISTORIAL_CLINICO_UPDATE_SP(
P_ID_HISTORIAL IN FIDE_HISTORIAL_CLINICO_TB.ID_HISTORIAL%TYPE,
P_ID_CITA IN FIDE_HISTORIAL_CLINICO_TB.ID_CITA%TYPE,
P_DIAGNOSTICO IN FIDE_HISTORIAL_CLINICO_TB.DIAGNOSTICO%TYPE,
P_PROCEDIMIENTOS_REALIZADOS IN FIDE_HISTORIAL_CLINICO_TB.PROCEDIMIENTOS_REALIZADOS%TYPE,
P_TRATAMIENTO_SUGERIDO IN FIDE_HISTORIAL_CLINICO_TB.TRATAMIENTO_SUGERIDO%TYPE
)IS
BEGIN
    UPDATE FIDE_HISTORIAL_CLINICO_TB
    SET ID_HISTORIAL = P_ID_HISTORIAL,
        ID_CITA = P_ID_CITA,
        DIAGNOSTICO = P_DIAGNOSTICO,
        PROCEDIMIENTOS_REALIZADOS = P_PROCEDIMIENTOS_REALIZADOS,
        TRATAMIENTO_SUGERIDO = P_TRATAMIENTO_SUGERIDO
    WHERE ID_HISTORIAL = P_ID_HISTORIAL;
END;

PROCEDURE FIDE_ALERGIA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ALERGIA_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;

PROCEDURE FIDE_PACIENTE_ENFERMEDAD_UPDATE_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_PACIENTE%TYPE,
P_ID_ENFERMEDAD IN FIDE_PACIENTE_ENFERMEDAD_TB.ID_ENFERMEDAD%TYPE,
P_FECHA_DIAGNOSTICO IN FIDE_PACIENTE_ENFERMEDAD_TB.FECHA_DIAGNOSTICO%TYPE,
P_NOTAS IN FIDE_PACIENTE_ENFERMEDAD_TB.NOTAS%TYPE
)IS 
BEGIN
    UPDATE FIDE_PACIENTE_ENFERMEDAD_TB
    SET 
        ID_PACIENTE = P_ID_PACIENTE,
        ID_ENFERMEDAD = P_ID_ENFERMEDAD,
        FECHA_DIAGNOSTICO = P_FECHA_DIAGNOSTICO,
        NOTAS = P_NOTAS
    WHERE ID_PACIENTE = P_ID_PACIENTE;
    COMMIT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_ALERGIA_UPDATE_SP(
P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
P_NOMBRE_ALERGIA IN FIDE_ALERGIA_TB.NOMBRE_ALERGIA%TYPE
)IS
BEGIN
    UPDATE FIDE_ALERGIA_TB
    SET ID_ALERGIA =P_ID_ALERGIA,
        NOMBRE_ALERGIA = P_NOMBRE_ALERGIA
    WHERE ID_ALERGIA = P_ID_ALERGIA;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_ENFERMEDAD_CRONICA_SELECT_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ENFERMEDAD_CRONICA_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar sucursales: ' || SQLERRM);
END;

-- CORREGIDO: SE RENOMBRÃ“ A FIDE_ENFERMEDAD_CRONICA_UPDATE_SP
PROCEDURE FIDE_ENFERMEDAD_CRONICA_UPDATE_SP(
P_ID_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.ID_ENFERMEDAD%TYPE,
P_NOMBRE_ENFERMEDAD IN FIDE_ENFERMEDAD_CRONICA_TB.NOMBRE_ENFERMEDAD%TYPE
)IS
BEGIN
    UPDATE FIDE_ENFERMEDAD_CRONICA_TB
    SET ID_ENFERMEDAD =P_ID_ENFERMEDAD,
        NOMBRE_ENFERMEDAD = P_NOMBRE_ENFERMEDAD
    WHERE ID_ENFERMEDAD = P_ID_ENFERMEDAD;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO HAY DATOS ENCONTRADOS');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR'||''|| SQLERRM);
END;

PROCEDURE FIDE_SUCURSAL_TB_INSERTAR_SP(
P_NOMBRE IN FIDE_SUCURSAL_TB.NOMBRE%TYPE,
P_ID_DIRECCION IN FIDE_SUCURSAL_TB.ID_DIRECCION%TYPE,
P_TELEFONO IN FIDE_SUCURSAL_TB.TELEFONO%TYPE,
P_ID_ESTADO IN FIDE_SUCURSAL_TB.ID_ESTADO%TYPE
)IS
    V_NUEVO_ID NUMBER; -- Variable temporal para guardar el ID
BEGIN

    INSERT INTO FIDE_SUCURSAL_TB(NOMBRE, ID_DIRECCION, TELEFONO, ID_ESTADO)
    VALUES(P_NOMBRE, P_ID_DIRECCION, P_TELEFONO, P_ID_ESTADO);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Sucursal insertada con ID: ' || V_NUEVO_ID);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inesperado al insertar sucursal: ' || SQLERRM);
END FIDE_SUCURSAL_TB_INSERTAR_SP;

PROCEDURE FIDE_SUCURSAL_TB_ACTUALIZAR_SP(
P_ID_SUCURSAL IN FIDE_SUCURSAL_TB.ID_SUCURSAL%TYPE,
P_NOMBRE IN FIDE_SUCURSAL_TB.NOMBRE%TYPE,
P_ID_DIRECCION IN FIDE_SUCURSAL_TB.ID_DIRECCION%TYPE,
P_TELEFONO IN FIDE_SUCURSAL_TB.TELEFONO%TYPE
)IS
BEGIN
    UPDATE FIDE_SUCURSAL_TB
    SET NOMBRE = P_NOMBRE, TELEFONO = P_TELEFONO, ID_DIRECCION = P_ID_DIRECCION
    WHERE ID_SUCURSAL = P_ID_SUCURSAL;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro la SUCURSAL con ID: ' || P_ID_SUCURSAL);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Sucursal actualizada correctamente.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al actualizar la sucursal: ' || SQLERRM);
END FIDE_SUCURSAL_TB_ACTUALIZAR_SP;

PROCEDURE FIDE_SUCURSAL_TB_ELIMINAR_SP(
P_ID_SUCURSAL IN FIDE_SUCURSAL_TB.ID_SUCURSAL%TYPE,
P_ID_ESTADO IN FIDE_SUCURSAL_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_SUCURSAL_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_SUCURSAL = P_ID_SUCURSAL;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro la SUCURSAL con ID: ' || P_ID_SUCURSAL);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Estado de la SUCURSAL actualizado correctamente.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al cambiar estado de sucursal: ' || SQLERRM);
END FIDE_SUCURSAL_TB_ELIMINAR_SP;

PROCEDURE FIDE_SUCURSAL_TB_LISTAR_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_SUCURSALES_V;
END FIDE_SUCURSAL_TB_LISTAR_SP;

PROCEDURE FIDE_SUCURSAL_TB_LISTAR_DROPDOWN_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT 
        S.ID_SUCURSAL, 
        S.NOMBRE, 
        S.TELEFONO, 
        S.ID_ESTADO,
        P.NOMBRE_PROVINCIA || ', ' || C.NOMBRE_CANTON || ', ' || D.NOMBRE_DISTRITO || ': ' || DIR.DETALLES AS DIRECCION_COMPLETA
    FROM FIDE_SUCURSAL_TB S
    INNER JOIN FIDE_DIRECCIONES_TB DIR ON S.ID_DIRECCION = DIR.ID_DIRECCION
    INNER JOIN FIDE_DISTRITOS_TB D ON DIR.ID_DISTRITO = D.ID_DISTRITO
    INNER JOIN FIDE_CANTONES_TB C ON D.ID_CANTON = C.ID_CANTON
    INNER JOIN FIDE_PROVINCIAS_TB P ON C.ID_PROVINCIA = P.ID_PROVINCIA
    WHERE S.ID_ESTADO = 1
    ORDER BY S.ID_SUCURSAL ASC;
END FIDE_SUCURSAL_TB_LISTAR_DROPDOWN_SP;

PROCEDURE FIDE_PERSONAL_TB_INSERTAR_SP(
P_NOMBRE IN FIDE_PERSONAL_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PERSONAL_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PERSONAL_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_CONTRATACION IN FIDE_PERSONAL_TB.FECHA_CONTRATACION%TYPE,
P_ID_SUCURSAL IN FIDE_PERSONAL_TB.ID_SUCURSAL%TYPE,
P_ID_ROL_PERSONAL IN FIDE_PERSONAL_TB.ID_ROL_PERSONAL%TYPE,
P_ID_ESTADO IN FIDE_PERSONAL_TB.ID_ESTADO%TYPE
)IS
    V_ID NUMBER;
BEGIN
    INSERT INTO FIDE_PERSONAL_TB (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_CONTRATACION, ID_SUCURSAL, ID_ROL_PERSONAL, ID_ESTADO)
    VALUES(P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_FECHA_CONTRATACION, P_ID_SUCURSAL, P_ID_ROL_PERSONAL, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Personal insertado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error insertando personal: ' || SQLERRM);
END FIDE_PERSONAL_TB_INSERTAR_SP;

-- CORREGIDO: SE AGREGÃ“ EL APELLIDO MATERNO AL BODY
PROCEDURE FIDE_PERSONAL_TB_ACTUALIZAR_SP(
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_NOMBRE IN FIDE_PERSONAL_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PERSONAL_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PERSONAL_TB.APELLIDO_MATERNO%TYPE,
P_ID_SUCURSAL IN FIDE_PERSONAL_TB.ID_SUCURSAL%TYPE,
P_ID_ROL_PERSONAL IN FIDE_PERSONAL_TB.ID_ROL_PERSONAL%TYPE
) IS
BEGIN
    UPDATE FIDE_PERSONAL_TB 
    SET NOMBRE = P_NOMBRE, 
        APELLIDO_PATERNO = P_APELLIDO_PATERNO, 
        APELLIDO_MATERNO = P_APELLIDO_MATERNO, -- AGREGADO
        ID_SUCURSAL = P_ID_SUCURSAL, 
        ID_ROL_PERSONAL = P_ID_ROL_PERSONAL 
    WHERE ID_PERSONAL = P_ID_PERSONAL;
    COMMIT;
END FIDE_PERSONAL_TB_ACTUALIZAR_SP;

PROCEDURE FIDE_PERSONAL_TB_ELIMINAR_SP(
P_ID_PERSONAL IN FIDE_PERSONAL_TB.ID_PERSONAL%TYPE,
P_ID_ESTADO IN FIDE_PERSONAL_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_PERSONAL_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_PERSONAL = P_ID_PERSONAL;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro PERSONAL con ID: '||P_ID_PERSONAL);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Estado del PERSONAL actualizado.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error soft-delete personal: ' || SQLERRM);
END FIDE_PERSONAL_TB_ELIMINAR_SP;

PROCEDURE FIDE_PERSONAL_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PERSONAL_V;
END FIDE_PERSONAL_TB_LISTAR_SP;

PROCEDURE FIDE_PACIENTE_TB_INSERTAR_SP(
P_NOMBRE IN FIDE_PACIENTE_TB.NOMBRE%TYPE,
P_APELLIDO_PATERNO IN FIDE_PACIENTE_TB.APELLIDO_PATERNO%TYPE,
P_APELLIDO_MATERNO IN FIDE_PACIENTE_TB.APELLIDO_MATERNO%TYPE,
P_FECHA_NACIMIENTO IN FIDE_PACIENTE_TB.FECHA_NACIMIENTO%TYPE,
P_ID_DIRECCION IN FIDE_PACIENTE_TB.ID_DIRECCION%TYPE,
P_ID_ESTADO IN FIDE_PACIENTE_TB.ID_ESTADO%TYPE
)IS
    V_ID NUMBER;
BEGIN
    INSERT INTO FIDE_PACIENTE_TB (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, ID_DIRECCION, ID_ESTADO)
    VALUES(P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_FECHA_NACIMIENTO, P_ID_DIRECCION, P_ID_ESTADO);
    COMMIT;
END FIDE_PACIENTE_TB_INSERTAR_SP;

PROCEDURE FIDE_PACIENTE_TB_ACTUALIZAR_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE, 
P_NOMBRE IN FIDE_PACIENTE_TB.NOMBRE%TYPE, 
P_APELLIDO_PATERNO IN FIDE_PACIENTE_TB.APELLIDO_PATERNO%TYPE, 
P_APELLIDO_MATERNO IN FIDE_PACIENTE_TB.APELLIDO_MATERNO%TYPE, 
P_ID_DIRECCION IN FIDE_PACIENTE_TB.ID_DIRECCION%TYPE) IS
BEGIN
    UPDATE FIDE_PACIENTE_TB 
    SET 
    NOMBRE = P_NOMBRE, 
    APELLIDO_PATERNO = P_APELLIDO_PATERNO, 
    APELLIDO_MATERNO = P_APELLIDO_MATERNO, 
    ID_DIRECCION = P_ID_DIRECCION 
    WHERE ID_PACIENTE = P_ID_PACIENTE;
    COMMIT;
END FIDE_PACIENTE_TB_ACTUALIZAR_SP;

PROCEDURE FIDE_PACIENTE_TB_ELIMINAR_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE, 
P_ID_ESTADO IN FIDE_PACIENTE_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_PACIENTE_TB SET ID_ESTADO = P_ID_ESTADO WHERE ID_PACIENTE = P_ID_PACIENTE;
    COMMIT;
END FIDE_PACIENTE_TB_ELIMINAR_SP;

PROCEDURE FIDE_PACIENTE_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PACIENTES_V;
END FIDE_PACIENTE_TB_LISTAR_SP;

PROCEDURE FIDE_USUARIO_TB_INSERTAR_SP(
P_NOMBRE_USUARIO IN FIDE_USUARIO_TB.NOMBRE_USUARIO%TYPE,
P_CONTRASENNA IN FIDE_USUARIO_TB.CONTRASENNA%TYPE,
P_ID_PERSONAL IN FIDE_USUARIO_TB.ID_PERSONAL%TYPE,
P_ID_PACIENTE IN FIDE_USUARIO_TB.ID_PACIENTE%TYPE,
P_ID_ROL_SISTEMA IN FIDE_USUARIO_TB.ID_ROL_SISTEMA%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
)IS
    V_NUEVO_ID NUMBER;
BEGIN

    INSERT INTO FIDE_USUARIO_TB(NOMBRE_USUARIO, CONTRASENNA, ID_PERSONAL, ID_PACIENTE, ID_ROL_SISTEMA, ID_ESTADO)
    VALUES(P_NOMBRE_USUARIO, P_CONTRASENNA, P_ID_PERSONAL, P_ID_PACIENTE, P_ID_ROL_SISTEMA, P_ID_ESTADO);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Usuario creado con ID: ' || V_NUEVO_ID);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creando usuario: ' || SQLERRM);
END FIDE_USUARIO_TB_INSERTAR_SP;

PROCEDURE FIDE_USUARIO_TB_ACTUALIZAR_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_ID_ROL_SISTEMA IN FIDE_USUARIO_TB.ID_ROL_SISTEMA%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET ID_ROL_SISTEMA = P_ID_ROL_SISTEMA,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_USUARIO = P_ID_USUARIO;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Usuario no encontrado.');
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Datos de usuario actualizados.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error actualizando usuario: ' || SQLERRM);
END FIDE_USUARIO_TB_ACTUALIZAR_SP;

PROCEDURE FIDE_USUARIO_TB_CAMBIAR_CLAVE_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NUEVA_CONTRASENNA IN FIDE_USUARIO_TB.CONTRASENNA%TYPE
)IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET CONTRASENNA = P_NUEVA_CONTRASENNA
    WHERE ID_USUARIO = P_ID_USUARIO;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Usuario no encontrado.');
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Clave actualizada.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error actualizando clave: ' || SQLERRM);
END FIDE_USUARIO_TB_CAMBIAR_CLAVE_SP;

PROCEDURE FIDE_USUARIO_TB_LISTAR_SP(
    P_CURSOR OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_USUARIO_TB;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar usuarios: ' || SQLERRM);
END FIDE_USUARIO_TB_LISTAR_SP;

PROCEDURE FIDE_FACTURA_TB_INSERTAR_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_CITA IN FIDE_FACTURA_TB.ID_CITA%TYPE,
P_FECHA_EMISION IN FIDE_FACTURA_TB.FECHA_EMISION%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
)IS
BEGIN
    INSERT INTO FIDE_FACTURA_TB(ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, MONTO_TOTAL, ID_ESTADO)
    VALUES(P_ID_CITA, P_FECHA_EMISION, P_SUBTOTAL, P_IVA, P_TOTAL, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Factura #' || P_ID_FACTURA || ' generada.');
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error generando factura: ' || SQLERRM);
END FIDE_FACTURA_TB_INSERTAR_SP;

PROCEDURE FIDE_FACTURA_TB_ANULAR_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_FACTURA_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_FACTURA = P_ID_FACTURA;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Factura no encontrada.');
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Factura Anulada (Soft Delete).');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error anulando factura: ' || SQLERRM);
END FIDE_FACTURA_TB_ANULAR_SP;

PROCEDURE FIDE_FACTURA_TB_LISTAR_SP(
    P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_FACTURA_TB;
EXCEPTION
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al listar facturas: ' || SQLERRM);
END FIDE_FACTURA_TB_LISTAR_SP;

PROCEDURE FIDE_ROL_SISTEMA_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ROL_SISTEMA_TB ORDER BY ID_ROL_SISTEMA ASC;
END FIDE_ROL_SISTEMA_TB_LISTAR_SP;


PROCEDURE FIDE_ESTADO_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_ESTADO_TB ORDER BY ID_ESTADO ASC;
END FIDE_ESTADO_TB_LISTAR_SP;

PROCEDURE FIDE_DASHBOARD_SP(
P_CANT_SUCURSALES OUT NUMBER,
P_CANT_PERSONAL OUT NUMBER,
P_CANT_USUARIOS OUT NUMBER,
P_CANT_FACTURAS OUT NUMBER
)IS
BEGIN
    -- 1. Contar Sucursales Activas
    SELECT COUNT(*) INTO P_CANT_SUCURSALES 
    FROM FIDE_SUCURSAL_TB 
    WHERE ID_ESTADO = 1;

     -- 2. Contar Personal Activo
    SELECT COUNT(*) INTO P_CANT_PERSONAL 
    FROM FIDE_PERSONAL_TB 
    WHERE ID_ESTADO = 1;

    -- 3. Contar Usuarios Activos
    SELECT COUNT(*) INTO P_CANT_USUARIOS 
    FROM FIDE_USUARIO_TB 
    WHERE ID_ESTADO = 1;

    -- 4. Contar Total de Facturas (Sin filtro de estado, historial completo)
    SELECT COUNT(*) INTO P_CANT_FACTURAS 
    FROM FIDE_FACTURA_TB;

EXCEPTION
    WHEN OTHERS THEN
        P_CANT_SUCURSALES := 0;
        P_CANT_PERSONAL := 0;
        P_CANT_USUARIOS := 0;
        P_CANT_FACTURAS := 0;
    DBMS_OUTPUT.PUT_LINE('Error obteniendo estadÃ­sticas: ' || SQLERRM);
END FIDE_DASHBOARD_SP;


PROCEDURE FIDE_ROL_PERSONAL_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM FIDE_ROL_PERSONAL_TB;
    END FIDE_ROL_PERSONAL_TB_LISTAR_SP;

PROCEDURE FIDE_DIRECCIONES_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM FIDE_DIRECCIONES_TB WHERE ID_ESTADO = 1;
    END FIDE_DIRECCIONES_TB_LISTAR_SP;


--IMPLEMENTACION UBICACION
PROCEDURE FIDE_PROVINCIAS_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_PROVINCIAS_TB ORDER BY NOMBRE_PROVINCIA;
END FIDE_PROVINCIAS_LISTAR_SP;

PROCEDURE FIDE_CANTONES_POR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_CANTONES_TB.ID_PROVINCIA%TYPE, 
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT * FROM FIDE_CANTONES_TB 
    WHERE ID_PROVINCIA = P_ID_PROVINCIA 
    ORDER BY NOMBRE_CANTON;
END FIDE_CANTONES_POR_PROVINCIA_SP;

PROCEDURE FIDE_DISTRITOS_POR_CANTON_SP(
P_ID_CANTON IN FIDE_DISTRITOS_TB.ID_CANTON%TYPE, 
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT * FROM FIDE_DISTRITOS_TB 
    WHERE ID_CANTON = P_ID_CANTON 
    ORDER BY NOMBRE_DISTRITO;
END FIDE_DISTRITOS_POR_CANTON_SP;

--INSERTAR DIRECCION Y RETORNAR EL ID
PROCEDURE FIDE_DIRECCIONES_INSERTAR_V2_SP(
P_ID_DISTRITO IN FIDE_DIRECCIONES_TB.ID_DISTRITO%TYPE,
P_DETALLES IN FIDE_DIRECCIONES_TB.DETALLES%TYPE,
P_NEW_ID OUT FIDE_DIRECCIONES_TB.ID_DIRECCION%TYPE
)IS
BEGIN
    
    INSERT INTO FIDE_DIRECCIONES_TB(ID_DISTRITO, DETALLES, ID_ESTADO)
    VALUES (P_ID_DISTRITO, P_DETALLES, 1)
    RETURNING ID_DIRECCION INTO P_NEW_ID;
    
    COMMIT;
    
END FIDE_DIRECCIONES_INSERTAR_V2_SP;

PROCEDURE FIDE_PACIENTES_OBTENER_FULL_SP(
P_ID_PACIENTE IN FIDE_PACIENTE_TB.ID_PACIENTE%TYPE,
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR
    SELECT * FROM FIDE_VISTA_PACIENTES_FULL
    WHERE ID_PACIENTE = P_ID_PACIENTE;
END FIDE_PACIENTES_OBTENER_FULL_SP;

PROCEDURE FIDE_SUCURSAL_OBTENER_FULL_SP(
P_ID_SUCURSAL IN FIDE_SUCURSAL_TB.ID_SUCURSAL%TYPE,
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_SUCURSALES_OBTENER_FULL_V
WHERE ID_SUCURSAL = P_ID_SUCURSAL;

END FIDE_SUCURSAL_OBTENER_FULL_SP;

--Actualizar Direccion
PROCEDURE FIDE_DIRECCIONES_ACTUALIZAR_SP(
P_ID_DIRECCION IN FIDE_DIRECCIONES_TB.ID_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCIONES_TB.ID_DISTRITO%TYPE,
P_DETALLES IN FIDE_DIRECCIONES_TB.DETALLES%TYPE
)IS
BEGIN
    UPDATE FIDE_DIRECCIONES_TB 
    SET ID_DISTRITO = P_ID_DISTRITO, 
        DETALLES = P_DETALLES
    WHERE ID_DIRECCION = P_ID_DIRECCION;
    COMMIT;
END FIDE_DIRECCIONES_ACTUALIZAR_SP;

-- IMPLEMENTACION MEDICAMENTOS
PROCEDURE FIDE_MEDICAMENTO_TB_INSERTAR_SP(
P_NOMBRE_COMERCIAL IN FIDE_MEDICAMENTO_TB.NOMBRE_COMERCIAL%TYPE,
P_PRINCIPIO_ACTIVO IN FIDE_MEDICAMENTO_TB.PRINCIPIO_ACTIVO%TYPE,
P_PRESENTACION IN FIDE_MEDICAMENTO_TB.PRESENTACION%TYPE,
P_PRECIO_VENTA IN FIDE_MEDICAMENTO_TB.PRECIO_VENTA%TYPE,
P_ID_ESTADO IN FIDE_MEDICAMENTO_TB.ID_ESTADO%TYPE
)IS
BEGIN
        -- ID generado por Trigger
    INSERT INTO FIDE_MEDICAMENTO_TB(NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, PRECIO_VENTA, ID_ESTADO)
    VALUES(P_NOMBRE_COMERCIAL, P_PRINCIPIO_ACTIVO, P_PRESENTACION, P_PRECIO_VENTA, P_ID_ESTADO);
    COMMIT;
END FIDE_MEDICAMENTO_TB_INSERTAR_SP;

PROCEDURE FIDE_MEDICAMENTO_TB_ACTUALIZAR_SP(
P_ID_MEDICAMENTO IN FIDE_MEDICAMENTO_TB.ID_MEDICAMENTO%TYPE,
P_NOMBRE_COMERCIAL IN FIDE_MEDICAMENTO_TB.NOMBRE_COMERCIAL%TYPE,
P_PRINCIPIO_ACTIVO IN FIDE_MEDICAMENTO_TB.PRINCIPIO_ACTIVO%TYPE,
P_PRESENTACION IN FIDE_MEDICAMENTO_TB.PRESENTACION%TYPE,
P_PRECIO_VENTA IN FIDE_MEDICAMENTO_TB.PRECIO_VENTA%TYPE
)IS
BEGIN
    UPDATE FIDE_MEDICAMENTO_TB 
    SET NOMBRE_COMERCIAL = P_NOMBRE_COMERCIAL, 
        PRINCIPIO_ACTIVO = P_PRINCIPIO_ACTIVO, 
        PRESENTACION = P_PRESENTACION,
        PRECIO_VENTA = P_PRECIO_VENTA
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
    COMMIT;
END FIDE_MEDICAMENTO_TB_ACTUALIZAR_SP;

PROCEDURE FIDE_MEDICAMENTO_TB_ELIMINAR_SP(
P_ID_MEDICAMENTO IN FIDE_MEDICAMENTO_TB.ID_MEDICAMENTO%TYPE,
P_ID_ESTADO IN FIDE_MEDICAMENTO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_MEDICAMENTO_TB SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
    COMMIT;
END FIDE_MEDICAMENTO_TB_ELIMINAR_SP;

PROCEDURE FIDE_MEDICAMENTO_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR
    SELECT * FROM FIDE_MEDICAMENTOS_INFO_V 
    ORDER BY NOMBRE_COMERCIAL, NOMBRE_SUCURSAL;
END FIDE_MEDICAMENTO_TB_LISTAR_SP;

PROCEDURE FIDE_MEDICAMENTO_OBTENER_SP(
P_ID_MEDICAMENTO IN FIDE_MEDICAMENTO_TB.ID_MEDICAMENTO%TYPE, 
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_MEDICAMENTO_TB WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
END FIDE_MEDICAMENTO_OBTENER_SP;


--IMPLEMENTACION INVENTARIO
PROCEDURE FIDE_INVENTARIO_TB_INSERTAR_SP(
P_ID_SUCURSAL IN FIDE_INVENTARIO_TB.ID_SUCURSAL%TYPE,
P_ID_MEDICAMENTO IN FIDE_INVENTARIO_TB.ID_MEDICAMENTO%TYPE,
P_STOCK IN FIDE_INVENTARIO_TB.STOCK%TYPE,
P_FECHA_VENCIMIENTO IN FIDE_INVENTARIO_TB.FECHA_VENCIMIENTO%TYPE,
P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    INSERT INTO FIDE_INVENTARIO_TB(ID_SUCURSAL, ID_MEDICAMENTO, STOCK, FECHA_VENCIMIENTO, ID_ESTADO)
    VALUES(P_ID_SUCURSAL, P_ID_MEDICAMENTO, P_STOCK, P_FECHA_VENCIMIENTO, P_ID_ESTADO);
    COMMIT;
END FIDE_INVENTARIO_TB_INSERTAR_SP;

PROCEDURE FIDE_INVENTARIO_TB_ACTUALIZAR_SP(
P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE,
P_STOCK IN FIDE_INVENTARIO_TB.STOCK%TYPE,
P_FECHA_VENCIMIENTO IN FIDE_INVENTARIO_TB.FECHA_VENCIMIENTO%TYPE,
P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_INVENTARIO_TB 
    SET STOCK = P_STOCK, 
        FECHA_VENCIMIENTO = P_FECHA_VENCIMIENTO, 
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_INVENTARIO = P_ID_INVENTARIO;
    COMMIT;
END FIDE_INVENTARIO_TB_ACTUALIZAR_SP;

PROCEDURE FIDE_INVENTARIO_TB_ELIMINAR_SP(
P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE, 
P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_INVENTARIO_TB SET ID_ESTADO = P_ID_ESTADO WHERE ID_INVENTARIO = P_ID_INVENTARIO;
    COMMIT;
END FIDE_INVENTARIO_TB_ELIMINAR_SP;

PROCEDURE FIDE_INVENTARIO_TB_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
OPEN P_CURSOR FOR SELECT * FROM FIDE_INVENTARIO_V;
END FIDE_INVENTARIO_TB_LISTAR_SP;

PROCEDURE FIDE_INVENTARIO_OBTENER_SP(
P_ID_INVENTARIO FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE, 
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_INVENTARIO_POR_ID_V WHERE ID_INVENTARIO = P_ID_INVENTARIO;
END FIDE_INVENTARIO_OBTENER_SP;


--OBTENER PRECIO
PROCEDURE FIDE_GET_PRECIO_ITEM_SP(P_TIPO IN NUMBER, P_ID_ITEM IN NUMBER, P_PRECIO OUT NUMBER) IS
BEGIN
    IF P_TIPO = 1 THEN -- Servicio
        SELECT PRECIO INTO P_PRECIO FROM FIDE_SERVICIO_TB WHERE ID_SERVICIO = P_ID_ITEM;
    ELSE -- Medicamento
        SELECT PRECIO_VENTA INTO P_PRECIO FROM FIDE_MEDICAMENTO_TB WHERE ID_MEDICAMENTO = P_ID_ITEM;
    END IF;
EXCEPTION WHEN OTHERS THEN P_PRECIO := 0;
END FIDE_GET_PRECIO_ITEM_SP;


--''''''''''''''''''''''''''''''''''''''''''''''''''CARRITO''''''''''''''''''''''''''''''''''''''''''''''''''

--AGREGAR ITEM (si ya existe, suma cantidad, si no, inserta)
PROCEDURE FIDE_CARRITO_AGREGAR_SP(
P_USUARIO_SISTEMA IN FIDE_CARRITO_TB.USUARIO_SISTEMA%TYPE,
P_ID_SERVICIO IN FIDE_CARRITO_TB.ID_SERVICIO%TYPE,
P_ID_MEDICAMENTO IN FIDE_CARRITO_TB.ID_MEDICAMENTO%TYPE
)IS
    V_CANTIDAD_ACTUAL NUMBER;
BEGIN

--primero se ve si ya existe
BEGIN
    SELECT CANTIDAD INTO V_CANTIDAD_ACTUAL
    FROM FIDE_CARRITO_TB
    WHERE USUARIO_SISTEMA = P_USUARIO_SISTEMA
        AND ((ID_SERVICIO = P_ID_SERVICIO) OR (ID_MEDICAMENTO = P_ID_MEDICAMENTO));
              
--si existe, actualizamos
    UPDATE FIDE_CARRITO_TB
    SET CANTIDAD = V_CANTIDAD_ACTUAL + 1
    WHERE USUARIO_SISTEMA = P_USUARIO_SISTEMA
    AND ((ID_SERVICIO = P_ID_SERVICIO) OR (ID_MEDICAMENTO = P_ID_MEDICAMENTO));
              
EXCEPTION WHEN NO_DATA_FOUND THEN
    --si no existe, insertamos con cantidad 1
    INSERT INTO FIDE_CARRITO_TB (USUARIO_SISTEMA, ID_SERVICIO, ID_MEDICAMENTO, CANTIDAD)
    VALUES (P_USUARIO_SISTEMA, P_ID_SERVICIO, P_ID_MEDICAMENTO, 1);
END;
        
    COMMIT;
END FIDE_CARRITO_AGREGAR_SP;

--ELIMINAR ITEM ESPECÍFICO
PROCEDURE FIDE_CARRITO_ELIMINAR_SP(
P_ID_CARRITO IN FIDE_CARRITO_TB.ID_CARRITO%TYPE
)IS
BEGIN
    DELETE FROM FIDE_CARRITO_TB WHERE ID_CARRITO = P_ID_CARRITO;
    COMMIT;
END FIDE_CARRITO_ELIMINAR_SP;

--LISTAR CARRITO (para la vista MiCarrito.php)
PROCEDURE FIDE_CARRITO_LISTAR_SP(
P_USUARIO_SISTEMA IN FIDE_CARRITO_TB.USUARIO_SISTEMA%TYPE,
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR
    SELECT 
        C.ID_CARRITO,
        C.CANTIDAD,
        --nombre
        CASE WHEN C.ID_SERVICIO IS NOT NULL THEN S.NOMBRE 
            ELSE M.NOMBRE_COMERCIAL || ' ' || M.PRESENTACION END AS NOMBRE_ITEM,
        --determinar precio unitario
        CASE WHEN C.ID_SERVICIO IS NOT NULL THEN S.PRECIO 
            ELSE M.PRECIO_VENTA END AS PRECIO_UNITARIO,
        --subtotal
        (C.CANTIDAD * (CASE WHEN C.ID_SERVICIO IS NOT NULL THEN S.PRECIO ELSE M.PRECIO_VENTA END)) AS SUBTOTAL,
        --IVA (13%)
        ((C.CANTIDAD * (CASE WHEN C.ID_SERVICIO IS NOT NULL THEN S.PRECIO ELSE M.PRECIO_VENTA END)) * 0.13) AS IMPUESTO,
        --Total
        ((C.CANTIDAD * (CASE WHEN C.ID_SERVICIO IS NOT NULL THEN S.PRECIO ELSE M.PRECIO_VENTA END)) * 1.13) AS TOTAL_LINEA
    FROM FIDE_CARRITO_TB C
    LEFT JOIN FIDE_SERVICIO_TB S ON C.ID_SERVICIO = S.ID_SERVICIO
    LEFT JOIN FIDE_MEDICAMENTO_TB M ON C.ID_MEDICAMENTO = M.ID_MEDICAMENTO
    WHERE C.USUARIO_SISTEMA = P_USUARIO_SISTEMA;
END FIDE_CARRITO_LISTAR_SP;


-- INSERTAR HEADER
PROCEDURE FIDE_FACTURA_INSERTAR_V2_SP(
P_ID_CITA IN FIDE_FACTURA_TB.ID_CITA%TYPE,
P_NUEVA_ID OUT FIDE_FACTURA_TB.ID_FACTURA%TYPE
)IS
BEGIN
    --Insertamos con montos en 0. Se calcularán conforme entren los detalles.
    INSERT INTO FIDE_FACTURA_TB(ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, MONTO_TOTAL, ID_ESTADO)
    VALUES(P_ID_CITA, SYSDATE, 0, 0, 0, 1)
    RETURNING ID_FACTURA INTO P_NUEVA_ID;
    COMMIT;
END FIDE_FACTURA_INSERTAR_V2_SP;

--INSERTAR DETALLE (Calculo Automatico)
PROCEDURE FIDE_FACTURA_DETALLE_INSERT_SP(
P_ID_FACTURA IN FIDE_FACTURA_DETALLE_TB.ID_FACTURA%TYPE,
P_ID_LINEA IN FIDE_FACTURA_DETALLE_TB.ID_LINEA%TYPE,
P_ID_INVENTARIO IN FIDE_FACTURA_DETALLE_TB.ID_INVENTARIO%TYPE,
P_ID_SERVICIO IN FIDE_FACTURA_DETALLE_TB.ID_SERVICIO%TYPE,
P_CANTIDAD IN FIDE_FACTURA_DETALLE_TB.CANTIDAD%TYPE
)IS
    V_PRECIO_UNITARIO DECIMAL(12,2);
    V_SUBTOTAL_LINEA DECIMAL(12,2);
    V_CONCEPTO VARCHAR2(100);
    V_TOTAL_FACTURA DECIMAL(12,2);
    V_IVA_FACTURA DECIMAL(12,2);
BEGIN
    -- 1.OBTENER PRECIO Y CONCEPTO DE LA BD
--si en el carrito añadimos un servicio o medicamento, se verifica aqui
IF P_ID_SERVICIO IS NOT NULL THEN
    SELECT PRECIO, NOMBRE INTO V_PRECIO_UNITARIO, V_CONCEPTO 
    FROM FIDE_SERVICIO_TB WHERE ID_SERVICIO = P_ID_SERVICIO;
ELSIF P_ID_INVENTARIO IS NOT NULL THEN

    --Se hace el JOIN para llegar al precio del medicamento desde el inventario
    SELECT M.PRECIO_VENTA, M.NOMBRE_COMERCIAL || ' ' || M.PRESENTACION 
    INTO V_PRECIO_UNITARIO, V_CONCEPTO
    FROM FIDE_INVENTARIO_TB I
    JOIN FIDE_MEDICAMENTO_TB M ON I.ID_MEDICAMENTO = M.ID_MEDICAMENTO
    WHERE I.ID_INVENTARIO = P_ID_INVENTARIO;
END IF;

-- 2.CALCULAMOS SUBTOTAL DE LINEA
V_SUBTOTAL_LINEA := V_PRECIO_UNITARIO * P_CANTIDAD; --LA CANTIDAD VIENE DE LA PAGINA WEB

-- 3.INSERTAMOS DETALLE
INSERT INTO FIDE_FACTURA_DETALLE_TB(
ID_FACTURA, 
ID_LINEA, 
CONCEPTO, 
ID_INVENTARIO, 
ID_SERVICIO, 
CANTIDAD, 
PRECIO_UNITARIO, 
SUBTOTAL
)
VALUES(
P_ID_FACTURA, 
P_ID_LINEA, 
V_CONCEPTO, 
P_ID_INVENTARIO, 
P_ID_SERVICIO, 
P_CANTIDAD, 
V_PRECIO_UNITARIO, 
V_SUBTOTAL_LINEA
);

-- 4.ACTUALIZAR FACTURA PADRE
-- Sumamos todo lo que hay en detalles para esta factura
UPDATE FIDE_FACTURA_TB F
SET 
    SUBTOTAL = (SELECT SUM(SUBTOTAL) FROM FIDE_FACTURA_DETALLE_TB WHERE ID_FACTURA = P_ID_FACTURA),
    IVA = (SELECT SUM(SUBTOTAL) * 0.13 FROM FIDE_FACTURA_DETALLE_TB WHERE ID_FACTURA = P_ID_FACTURA),
    MONTO_TOTAL = (SELECT SUM(SUBTOTAL) * 1.13 FROM FIDE_FACTURA_DETALLE_TB WHERE ID_FACTURA = P_ID_FACTURA)
WHERE ID_FACTURA = P_ID_FACTURA;

COMMIT;

EXCEPTION
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('Error en Detalle: ' || SQLERRM);
        ROLLBACK;
END FIDE_FACTURA_DETALLE_INSERT_SP;

---------SERVICIO-----------

--LISTAR SERVICIOS
PROCEDURE FIDE_SERVICIO_TB_LISTAR_SP(
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_SERVICIO_TB ORDER BY NOMBRE;
END FIDE_SERVICIO_TB_LISTAR_SP;

PROCEDURE FIDE_SERVICIO_TB_INSERTAR_SP(
P_NOMBRE IN FIDE_SERVICIO_TB.NOMBRE%TYPE,
P_DESCRIPCION IN FIDE_SERVICIO_TB.DESCRIPCION%TYPE,
P_PRECIO IN FIDE_SERVICIO_TB.PRECIO%TYPE,
P_ID_ESTADO IN FIDE_SERVICIO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    INSERT INTO FIDE_SERVICIO_TB(NOMBRE, DESCRIPCION, PRECIO, ID_ESTADO)
    VALUES(P_NOMBRE, P_DESCRIPCION, P_PRECIO, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Servicio insertado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error insertando servicio: ' || SQLERRM);
END FIDE_SERVICIO_TB_INSERTAR_SP;


PROCEDURE FIDE_SERVICIO_TB_ACTUALIZAR_SP(
P_ID_SERVICIO IN FIDE_SERVICIO_TB.ID_SERVICIO%TYPE,
P_NOMBRE IN FIDE_SERVICIO_TB.NOMBRE%TYPE,
P_DESCRIPCION IN FIDE_SERVICIO_TB.DESCRIPCION%TYPE,
P_PRECIO IN FIDE_SERVICIO_TB.PRECIO%TYPE
)IS
BEGIN
    UPDATE FIDE_SERVICIO_TB 
    SET NOMBRE = P_NOMBRE, 
        DESCRIPCION = P_DESCRIPCION, 
        PRECIO = P_PRECIO
    WHERE ID_SERVICIO = P_ID_SERVICIO;
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se encontró el Servicio con ID: ' || P_ID_SERVICIO);
    ELSE
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Servicio actualizado correctamente.');
    END IF;
END FIDE_SERVICIO_TB_ACTUALIZAR_SP;


PROCEDURE FIDE_SERVICIO_TB_ELIMINAR_SP(
P_ID_SERVICIO IN FIDE_SERVICIO_TB.ID_SERVICIO%TYPE,
P_ID_ESTADO IN FIDE_SERVICIO_TB.ID_ESTADO%TYPE
)IS
BEGIN
    UPDATE FIDE_SERVICIO_TB 
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_SERVICIO = P_ID_SERVICIO;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error cambiando estado servicio: ' || SQLERRM);
END FIDE_SERVICIO_TB_ELIMINAR_SP;


PROCEDURE FIDE_SERVICIO_TB_OBTENER_SP(
P_ID_SERVICIO IN FIDE_SERVICIO_TB.ID_SERVICIO%TYPE, 
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT * FROM FIDE_SERVICIO_TB 
    WHERE ID_SERVICIO = P_ID_SERVICIO;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error obteniendo servicio: ' || SQLERRM);
END FIDE_SERVICIO_TB_OBTENER_SP;


--OBTENER CITAS PENDIENTES (dropdown)
--Traemos Citas activas (Estado 3 segun la logica) y concatenamos info para el usuario
PROCEDURE FIDE_CITAS_PENDIENTES_SP(P_CURSOR OUT SYS_REFCURSOR) IS

BEGIN
    OPEN P_CURSOR FOR
    SELECT 
        C.ID_CITA,
        P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' (' || S.NOMBRE || ')' AS INFO_CITA
    FROM FIDE_CITA_TB C
    JOIN FIDE_PACIENTE_TB P ON C.ID_PACIENTE = P.ID_PACIENTE
    JOIN FIDE_SUCURSAL_TB S ON C.ID_SUCURSAL = S.ID_SUCURSAL
    WHERE C.ID_ESTADO IN (3, 4)
    AND NOT EXISTS (SELECT 1 FROM FIDE_FACTURA_TB F WHERE F.ID_CITA = C.ID_CITA AND F.ID_ESTADO <> 5); -- Que no esté facturada
    
END FIDE_CITAS_PENDIENTES_SP;
    
--REALIZAR PAGO (FACTURAR)
PROCEDURE FIDE_FACTURAR_CARRITO_SP(
P_USUARIO_SISTEMA IN FIDE_CARRITO_TB.USUARIO_SISTEMA%TYPE,
P_ID_CITA IN FIDE_CITA_TB.ID_CITA%TYPE,
P_NUEVO_ID_FACTURA OUT FIDE_FACTURA_TB.ID_FACTURA%TYPE
)IS
V_ID_FACTURA FIDE_FACTURA_TB.ID_FACTURA%TYPE;
V_SUBTOTAL FIDE_FACTURA_TB.SUBTOTAL%TYPE := 0;
V_IVA FIDE_FACTURA_TB.IVA%TYPE := 0;
V_TOTAL FIDE_FACTURA_TB.MONTO_TOTAL%TYPE := 0;
V_SUCURSAL_CITA FIDE_CITA_TB.ID_SUCURSAL%TYPE;
V_LINEA NUMBER := 1;
    
    --variable para gestionar el inventario detectado
V_ID_INVENTARIO_TEMP  FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE;
    
CURSOR C_ITEMS IS
    SELECT C.ID_SERVICIO, C.ID_MEDICAMENTO, C.CANTIDAD,
        CASE WHEN C.ID_SERVICIO IS NOT NULL THEN S.PRECIO ELSE M.PRECIO_VENTA END AS PRECIO,
        CASE WHEN C.ID_SERVICIO IS NOT NULL THEN S.NOMBRE ELSE M.NOMBRE_COMERCIAL END AS CONCEPTO
    FROM FIDE_CARRITO_TB C
    LEFT JOIN FIDE_SERVICIO_TB S ON C.ID_SERVICIO = S.ID_SERVICIO
    LEFT JOIN FIDE_MEDICAMENTO_TB M ON C.ID_MEDICAMENTO = M.ID_MEDICAMENTO
    WHERE C.USUARIO_SISTEMA = P_USUARIO_SISTEMA;
        
BEGIN
--obtener la sucursal de la cita
SELECT ID_SUCURSAL INTO V_SUCURSAL_CITA FROM FIDE_CITA_TB WHERE ID_CITA = P_ID_CITA;

--INSERTAR CABECERA
INSERT INTO FIDE_FACTURA_TB (ID_CITA, FECHA_EMISION, SUBTOTAL, IVA, MONTO_TOTAL, ID_ESTADO)
VALUES (P_ID_CITA, SYSDATE, 0, 0, 0, 1)
RETURNING ID_FACTURA INTO V_ID_FACTURA;

P_NUEVO_ID_FACTURA := V_ID_FACTURA;

    --3 procesar items
FOR ITEM IN C_ITEMS LOOP
        
        -- inicializar variable temporal
V_ID_INVENTARIO_TEMP := NULL;

        --a. si es Medicamento, buscar el lote de inventario especifico en la sucursal
IF ITEM.ID_MEDICAMENTO IS NOT NULL THEN
    BEGIN
        SELECT ID_INVENTARIO INTO V_ID_INVENTARIO_TEMP
        FROM FIDE_INVENTARIO_TB
        WHERE ID_MEDICAMENTO = ITEM.ID_MEDICAMENTO 
            AND ID_SUCURSAL = V_SUCURSAL_CITA
            AND STOCK >= ITEM.CANTIDAD --verificar que alcance
            AND ROWNUM = 1; --tomar el primero disponible (FIFO simplificado)
                  
        --descontar el stock inmediatamente
        UPDATE FIDE_INVENTARIO_TB 
        SET STOCK = STOCK - ITEM.CANTIDAD
        WHERE ID_INVENTARIO = V_ID_INVENTARIO_TEMP;

    EXCEPTION WHEN NO_DATA_FOUND THEN
            --si no hay stock, lanzamos error específico
            RAISE_APPLICATION_ERROR(-20003, 'No hay stock suficiente para el medicamento en esta sucursal.');
    END;
END IF;

        --b insertar Detalle (usando ID_INVENTARIO o NULL si es servicio)
INSERT INTO FIDE_FACTURA_DETALLE_TB (ID_FACTURA, ID_LINEA, CONCEPTO, ID_INVENTARIO, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES( V_ID_FACTURA, V_LINEA,  ITEM.CONCEPTO, V_ID_INVENTARIO_TEMP, ITEM.ID_SERVICIO, ITEM.CANTIDAD, ITEM.PRECIO, (ITEM.CANTIDAD * ITEM.PRECIO)
);

        V_LINEA := V_LINEA + 1;
    END LOOP;

    -- 4 calcular totales finales
    SELECT SUM(SUBTOTAL) INTO V_SUBTOTAL FROM FIDE_FACTURA_DETALLE_TB WHERE ID_FACTURA = V_ID_FACTURA;
    
    --validación por si el subtotal quedó nulo
    IF V_SUBTOTAL IS NULL THEN V_SUBTOTAL := 0; END IF;
    
    V_IVA := V_SUBTOTAL * 0.13;
    V_TOTAL := V_SUBTOTAL + V_IVA;

    UPDATE FIDE_FACTURA_TB 
    SET SUBTOTAL = V_SUBTOTAL, IVA = V_IVA, MONTO_TOTAL = V_TOTAL
    WHERE ID_FACTURA = V_ID_FACTURA;
    
    -- 5 actualizar estado de la Cita (Cerrarla)
    UPDATE FIDE_CITA_TB SET ID_ESTADO = 4 WHERE ID_CITA = P_ID_CITA;
    
    -- 6 limpiar Carrito
    DELETE FROM FIDE_CARRITO_TB WHERE USUARIO_SISTEMA = P_USUARIO_SISTEMA;
    
    COMMIT;

EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20002, 'Error al facturar: ' || SQLERRM);
END FIDE_FACTURAR_CARRITO_SP;

PROCEDURE FIDE_FACTURA_LISTAR_SP(P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_FACTURAS_V ORDER BY ID_FACTURA DESC;
END FIDE_FACTURA_LISTAR_SP;

--OBTENER ENCABEZADO DE UNA (PARA LA VISTA DETALLE)
PROCEDURE FIDE_FACTURA_OBTENER_ENCABEZADO_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM FIDE_FACTURAS_V WHERE ID_FACTURA = P_ID_FACTURA;
END FIDE_FACTURA_OBTENER_ENCABEZADO_SP;

--OBTENER DETALLES DE UNA (Items comprados)
PROCEDURE FIDE_FACTURA_DETALLE_OBTENER_DETALLES_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_CURSOR OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT CONCEPTO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL 
    FROM FIDE_FACTURA_DETALLE_TB 
    WHERE ID_FACTURA = P_ID_FACTURA;
END FIDE_FACTURA_DETALLE_OBTENER_DETALLES_SP;

-------FUNCIONES---------

FUNCTION FIDE_CALCULAR_VENTAS_SUCURSAL_FN(
    P_ID_SUCURSAL NUMBER
) RETURN NUMBER IS
        V_TOTAL_VENTAS NUMBER := 0;
    CURSOR C_FACTURAS IS
    SELECT F.MONTO_TOTAL 
    FROM FIDE_FACTURA_TB F
    JOIN FIDE_CITA_TB C ON F.ID_CITA = C.ID_CITA
    WHERE C.ID_SUCURSAL = P_ID_SUCURSAL AND F.ID_ESTADO = 1;
BEGIN
    FOR R_FACTURA IN C_FACTURAS LOOP
            V_TOTAL_VENTAS := V_TOTAL_VENTAS + R_FACTURA.MONTO_TOTAL;
    END LOOP;
    RETURN V_TOTAL_VENTAS;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en funcion ventas: ' || SQLERRM);
        RETURN 0;
END FIDE_CALCULAR_VENTAS_SUCURSAL_FN;

FUNCTION FIDE_CONTAR_PERSONAL_ROL_FN(
    P_ID_ROL NUMBER
) RETURN NUMBER IS
    V_CANTIDAD NUMBER := 0;
    CURSOR C_PERSONAL IS
        SELECT ID_ROL_PERSONAL FROM FIDE_PERSONAL_TB;
    BEGIN
    FOR R_PERSONAL IN C_PERSONAL LOOP
        IF (R_PERSONAL.ID_ROL_PERSONAL = P_ID_ROL) THEN
                V_CANTIDAD := V_CANTIDAD + 1;
        END IF;
    END LOOP;
    RETURN V_CANTIDAD;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en funcion contar: ' || SQLERRM);
    RETURN 0;
END FIDE_CONTAR_PERSONAL_ROL_FN;

FUNCTION FIDE_ALERGIAS_PACIENTES_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    -- Cursor de Pacientes
    CURSOR PACIENTES IS SELECT ID_PACIENTE, NOMBRE || ' ' || APELLIDO_PATERNO AS NOMBRE_COMPLETO FROM FIDE_PACIENTE_TB;
    -- Cursor de Alergias
    CURSOR ALERGIAS IS SELECT ID_PACIENTE FROM FIDE_PACIENTE_ALERGIA_TB;
BEGIN
    FOR PACIENTE IN PACIENTES LOOP
        V_CONTADOR := 0;

        FOR ALERGIA IN ALERGIAS LOOP
            IF (ALERGIA.ID_PACIENTE = PACIENTE.ID_PACIENTE) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ALERGIAS REGISTRADAS PARA EL PACIENTE: ' || 
            PACIENTE.NOMBRE_COMPLETO
        );
    END LOOP;

    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN FUNCION ALERGIAS: ' || SQLERRM);
        RETURN 0;
END FIDE_ALERGIAS_PACIENTES_FN;

FUNCTION FIDE_CITAS_MEDICOS_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    -- Cursor de Medicos/Personal
    CURSOR MEDICOS IS SELECT ID_PERSONAL, NOMBRE || ' ' || APELLIDO_PATERNO AS NOMBRE_MEDICO FROM FIDE_PERSONAL_TB; 
    -- Cursor de Citas
    CURSOR CITAS IS SELECT ID_MEDICO FROM FIDE_CITA_TB;
BEGIN
    FOR MEDICO IN MEDICOS LOOP
        V_CONTADOR := 0;

        FOR CITA IN CITAS LOOP
            IF (CITA.ID_MEDICO = MEDICO.ID_PERSONAL) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        -- Opcional: Mostrar solo si tiene citas (quita el IF si quieres ver todos)
        IF V_CONTADOR >= 0 THEN 
            DBMS_OUTPUT.PUT_LINE(
                V_CONTADOR || ' CITAS PROGRAMADAS PARA EL MEDICO: ' || 
                MEDICO.NOMBRE_MEDICO
            );
        END IF;
    END LOOP;

    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN FUNCION CITAS MEDICOS: ' || SQLERRM);
        RETURN 0;
END FIDE_CITAS_MEDICOS_FN;

FUNCTION FIDE_CITAS_SUCURSALES_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    -- Cursor de Sucursales
    CURSOR SUCURSALES IS SELECT ID_SUCURSAL, NOMBRE FROM FIDE_SUCURSAL_TB;
    -- Cursor de Citas
    CURSOR CITAS IS SELECT ID_SUCURSAL FROM FIDE_CITA_TB;
BEGIN
    FOR SUCURSAL IN SUCURSALES LOOP
        V_CONTADOR := 0;

        FOR CITA IN CITAS LOOP
            IF (CITA.ID_SUCURSAL = SUCURSAL.ID_SUCURSAL) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' CITAS REGISTRADAS EN LA SUCURSAL: ' || 
            SUCURSAL.NOMBRE
        );
    END LOOP;

    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN FUNCION CITAS SUCURSALES: ' || SQLERRM);
        RETURN 0;
END FIDE_CITAS_SUCURSALES_FN;

FUNCTION FIDE_DIRECCIONES_DISTRITOS_FN
RETURN NUMBER 
IS
    V_CONTADOR NUMBER := 0;
    CURSOR DISTRITOS IS SELECT ID_DISTRITO, NOMBRE_DISTRITO FROM FIDE_DISTRITOS_TB; 
    CURSOR DIRECCIONES IS SELECT ID_DISTRITO FROM FIDE_DIRECCIONES_TB; 
BEGIN

    FOR DISTRITO IN DISTRITOS LOOP
        V_CONTADOR:=0;

        FOR DIRECCION IN DIRECCIONES LOOP
            IF (DIRECCION.ID_DISTRITO = DISTRITO.ID_DISTRITO) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ' || 
            'DIRECCIONES EN EL DISTRITO ' || ' ' || 
            DISTRITO.NOMBRE_DISTRITO
        );
    END LOOP;

    RETURN 1; 

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN LA FUNCION: ' || SQLERRM);
        RETURN 0;
END FIDE_DIRECCIONES_DISTRITOS_FN;

FUNCTION FIDE_DIRECCIONES_PACIENTES_FN
RETURN NUMBER 
IS
    V_CONTADOR NUMBER := 0;
    CURSOR PACIENTES IS SELECT * FROM FIDE_PACIENTE_TB;
    CURSOR DIRECCIONES IS SELECT ID_DIRECCION, DETALLES FROM FIDE_DIRECCIONES_TB; -- Asumo la columna DETALLES
BEGIN

    FOR DIRECCION IN DIRECCIONES LOOP
        V_CONTADOR:=0;

        FOR PACIENTE IN PACIENTES LOOP
            IF (PACIENTE.ID_DIRECCION = DIRECCION.ID_DIRECCION) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ' || 
            'PACIENTES EN LA DIRECCION ' || ' ' || 
            DIRECCION.DETALLES
        );
    END LOOP;
    RETURN 1;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN LA FUNCION: ' || SQLERRM);
        RETURN 0;
END FIDE_DIRECCIONES_PACIENTES_FN;

FUNCTION FIDE_ENFERMEDADES_PACIENTES_FN
RETURN NUMBER
IS
    V_CONTADOR NUMBER := 0;
    CURSOR ENFERMEDADES IS SELECT ID_ENFERMEDAD, NOMBRE_ENFERMEDAD FROM FIDE_ENFERMEDAD_CRONICA_TB;
    CURSOR PACIENTES IS SELECT ID_ENFERMEDAD FROM FIDE_PACIENTE_ENFERMEDAD_TB;
BEGIN
    FOR ENFERMEDAD IN ENFERMEDADES LOOP
        V_CONTADOR:=0;

        FOR PACIENTE IN PACIENTES LOOP
            IF (PACIENTE.ID_ENFERMEDAD = ENFERMEDAD.ID_ENFERMEDAD) THEN
                V_CONTADOR := V_CONTADOR + 1;
            END IF;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE(
            V_CONTADOR || ' ' || 
            'PACIENTES CON LA ENFERMEDAD: ' || ' ' || 
            ENFERMEDAD.NOMBRE_ENFERMEDAD
        );
    END LOOP;
    RETURN 1;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        RETURN 0;
END FIDE_ENFERMEDADES_PACIENTES_FN;

FUNCTION FIDE_FACTURA_ID_COMPUESTO_FN
RETURN NUMBER AS 
    V_FECHA VARCHAR2(8);
    V_ID_GENERADO NUMBER;
BEGIN 
    V_FECHA := TO_CHAR(SYSDATE, 'YYYYMMDD');
    -- Concatenamos Fecha + Secuencia con relleno de ceros (LPAD)
    -- OJO: TO_NUMBER convierte todo el string a un nï¿½mero gigante
    V_ID_GENERADO := TO_NUMBER(V_FECHA || LPAD(ID_FACTURA_SEQ.NEXTVAL, 5, '0')); 
    RETURN V_ID_GENERADO;
END FIDE_FACTURA_ID_COMPUESTO_FN;

END FIDE_SALUDTOTAL_PKG;

/
