
-------------------------------SECUENCIAS------------------------------------

CREATE SEQUENCE ID_PACIENTE_SEQ
START WITH 33
INCREMENT BY 1;
-----------------------------------------
CREATE SEQUENCE ID_PERSONAL_SEQ 
START WITH 14 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_ROL_PERSONAL_SEQ 
START WITH 6 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_ROL_SISTEMA_SEQ 
START WITH 5 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_USUARIO_SEQ 
START WITH 15 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_SUCURSAL_SEQ 
START WITH 10 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_CITA_SEQ 
START WITH 151 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_CANTON_SEQ 
START WITH 23 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_ALERGIA_SEQ 
START WITH 8 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_DIRECCION_SEQ 
START WITH 11 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_DISTRITO_SEQ 
START WITH 23 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_ENFERMEDAD_CRONICA_SEQ 
START WITH 8 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_ESTADO_SEQ 
START WITH 6 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_HISTORIAL_CLINICO_SEQ 
START WITH 6 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_INVENTARIO_SEQ 
START WITH 35 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_MEDICAMENTO_SEQ 
START WITH 16 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_PROVINCIA_SEQ 
START WITH 8 INCREMENT BY 1;
---------------------------------------------
CREATE SEQUENCE ID_FACTURA_SEQ
START WITH 151
INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_SERVICIO_SEQ 
START WITH 1 INCREMENT BY 1;
--------------------------------------------
CREATE SEQUENCE ID_CARRITO_SEQ 
START WITH 1 INCREMENT BY 1;
---SECUENCIA "ESPECIAL"(COMPUESTA) PARA FACTURA

CREATE OR REPLACE FUNCTION FIDE_FACTURA_ID_COMPUESTO_FN
RETURN NUMBER AS 
    V_FECHA VARCHAR2(8);
    V_ID_GENERADO NUMBER;
BEGIN 
    V_FECHA := TO_CHAR(SYSDATE, 'YYYYMMDD');
    -- Concatenamos Fecha + Secuencia con relleno de ceros (LPAD)
    -- OJO: TO_NUMBER convierte todo el string a un n�mero gigante
    V_ID_GENERADO := TO_NUMBER(V_FECHA || LPAD(ID_FACTURA_SEQ.NEXTVAL, 5, '0')); 
    RETURN V_ID_GENERADO;
END FIDE_FACTURA_ID_COMPUESTO_FN;

--- FIN SECUENCIA "ESPECIAL"(COMPUESTA) PARA FACTURAS

--NOTA: TABLAS INTERMEDIAS NO LLEVAN SECUENCIA(PORQUE SON LLAVE COMPUESTA,
--EL ID VIENE YA DE OTRA TABLA) PERO SI DEBE DE HACERSE LA AUDITORIA
-------------------------------FIN SECUENCIAS------------------------------------



-------------------------------TRIGGERS------------------------------------
------------  TRIGGERS DE INSERT  -----------------------
-- *** FIDE_PACIENTE_TB ***
CREATE OR REPLACE TRIGGER FIDE_PACIENTE_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_PACIENTE_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');--NOMBRE DE QUIEN LO CREO
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_PACIENTE :=ID_PACIENTE_SEQ.NEXTVAL;
END;
/

-- *** FIDE_PERSONAL_TB ***
CREATE OR REPLACE TRIGGER FIDE_PERSONAL_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_PERSONAL_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_PERSONAL :=ID_PERSONAL_SEQ.NEXTVAL;
END;
/

-- *** FIDE_ROL_PERSONAL_TB ***
CREATE OR REPLACE TRIGGER FIDE_ROL_PERSONAL_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_ROL_PERSONAL_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_ROL_PERSONAL :=ID_ROL_PERSONAL_SEQ.NEXTVAL;
END;
/

-- *** FIDE_ROL_SISTEMA_TB ***
CREATE OR REPLACE TRIGGER FIDE_ROL_SISTEMA_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_ROL_SISTEMA_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_ROL_SISTEMA :=ID_ROL_SISTEMA_SEQ.NEXTVAL;
END;
/

-- *** FIDE_USUARIO_TB ***
CREATE OR REPLACE TRIGGER FIDE_USUARIO_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_USUARIO :=ID_USUARIO_SEQ.NEXTVAL;
END;
/

-- *** FIDE_SUCURSAL_TB ***
CREATE OR REPLACE TRIGGER FIDE_SUCURSAL_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_SUCURSAL_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_SUCURSAL :=ID_SUCURSAL_SEQ.NEXTVAL;
END;
/

-- *** FIDE_CITA_TB ***
CREATE OR REPLACE TRIGGER FIDE_CITA_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_CITA_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_CITA :=ID_CITA_SEQ.NEXTVAL;
END;
/

-- *** FIDE_CANTONES_TB ***
CREATE OR REPLACE TRIGGER FIDE_CANTONES_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_CANTON :=ID_CANTON_SEQ.NEXTVAL;
END;
/

-- *** FIDE_ALERGIA_TB ***
CREATE OR REPLACE TRIGGER FIDE_ALERGIA_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_ALERGIA_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_ALERGIA :=ID_ALERGIA_SEQ.NEXTVAL;
END;
/

-- *** FIDE_DIRECCIONES_TB ***
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_DIRECCION :=ID_DIRECCION_SEQ.NEXTVAL;
END;
/

-- *** FIDE_DISTRITOS_TB ***
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_DISTRITO :=ID_DISTRITO_SEQ.NEXTVAL;
END;
/

-- *** FIDE_ENFERMEDAD_CRONICA_TB ***
CREATE OR REPLACE TRIGGER FIDE_ENFERMEDAD_CRONICA_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_ENFERMEDAD_CRONICA_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_ENFERMEDAD :=ID_ENFERMEDAD_CRONICA_SEQ.NEXTVAL;
END;
/

-- *** FIDE_ESTADO_TB ***
CREATE OR REPLACE TRIGGER FIDE_ESTADO_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_ESTADO :=ID_ESTADO_SEQ.NEXTVAL;
END;
/

-- *** FIDE_HISTORIAL_CLINICO_TB ***
CREATE OR REPLACE TRIGGER FIDE_HISTORIAL_CLINICO_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_HISTORIAL_CLINICO_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_HISTORIAL :=ID_HISTORIAL_CLINICO_SEQ.NEXTVAL;
END;
/

-- *** FIDE_INVENTARIO_TB ***
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_INVENTARIO :=ID_INVENTARIO_SEQ.NEXTVAL;
END;
/

-- *** FIDE_MEDICAMENTO_TB ***
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTO_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_MEDICAMENTO_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_MEDICAMENTO :=ID_MEDICAMENTO_SEQ.NEXTVAL;
END;
/

-- *** FIDE_PROVINCIAS_TB ***
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_PROVINCIA :=ID_PROVINCIA_SEQ.NEXTVAL;
END;
/
-- *** FIDE_FACTURA_DETALLE_TB ***
CREATE OR REPLACE TRIGGER FIDE_FACTURA_DETALLE_INSERT_TRG
BEFORE INSERT ON FIDE_FACTURA_DETALLE_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
END;
/

-- *** FIDE_PACIENTE_ALERGIA_TB ***
CREATE OR REPLACE TRIGGER FIDE_PACIENTE_ALERGIA_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_PACIENTE_ALERGIA_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
END;
/

-- *** FIDE_PACIENTE_ENFERMEDAD_TB ***
CREATE OR REPLACE TRIGGER FIDE_PACIENTE_ENFERMEDAD_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_PACIENTE_ENFERMEDAD_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
END;
/

--------- TRIGGERS DE UPDATE  ---------------

-- *** FIDE_PACIENTE_TB ***
CREATE OR REPLACE TRIGGER FIDE_PACIENTE_UPDATE_TRG
BEFORE UPDATE ON FIDE_PACIENTE_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_PERSONAL_TB ***
CREATE OR REPLACE TRIGGER FIDE_PERSONAL_UPDATE_TRG
BEFORE UPDATE ON FIDE_PERSONAL_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_ROL_PERSONAL_TB ***
CREATE OR REPLACE TRIGGER FIDE_ROL_PERSONAL_UPDATE_TRG
BEFORE UPDATE ON FIDE_ROL_PERSONAL_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_ROL_SISTEMA_TB ***
CREATE OR REPLACE TRIGGER FIDE_ROL_SISTEMA_UPDATE_TRG
BEFORE UPDATE ON FIDE_ROL_SISTEMA_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_USUARIO_TB ***
CREATE OR REPLACE TRIGGER FIDE_USUARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_SUCURSAL_TB ***
CREATE OR REPLACE TRIGGER FIDE_SUCURSAL_UPDATE_TRG
BEFORE UPDATE ON FIDE_SUCURSAL_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_CITA_TB ***
CREATE OR REPLACE TRIGGER FIDE_CITA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CITA_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_CANTONES_TB ***
CREATE OR REPLACE TRIGGER FIDE_CANTONES_UPDATE_TRG
BEFORE UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_ALERGIA_TB ***
CREATE OR REPLACE TRIGGER FIDE_ALERGIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_ALERGIA_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_DIRECCIONES_TB ***
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_UPDATE_TRG
BEFORE UPDATE ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_DISTRITOS_TB ***
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_UPDATE_TRG
BEFORE UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_ENFERMEDAD_CRONICA_TB ***
CREATE OR REPLACE TRIGGER FIDE_ENFERMEDAD_CRONICA_UPDATE_TRG
BEFORE UPDATE ON FIDE_ENFERMEDAD_CRONICA_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_ESTADO_TB ***
CREATE OR REPLACE TRIGGER FIDE_ESTADO_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_HISTORIAL_CLINICO_TB ***
CREATE OR REPLACE TRIGGER FIDE_HISTORIAL_CLINICO_UPDATE_TRG
BEFORE UPDATE ON FIDE_HISTORIAL_CLINICO_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_INVENTARIO_TB ***
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_MEDICAMENETO_TB ***
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_MEDICAMENTO_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/

-- *** FIDE_PROVINCIAS_TB ***
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_UPDATE_TRG
BEFORE UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/
-- *** FIDE_FACTURA_DETALLE_TB ***
CREATE OR REPLACE TRIGGER FIDE_FACTURA_DETALLE_UPDATE_TRG
BEFORE UPDATE ON FIDE_FACTURA_DETALLE_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/
-- *** FIDE_PACIENTE_ALERGIA_TB ***
CREATE OR REPLACE TRIGGER FIDE_PACIENTE_ALERGIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_PACIENTE_ALERGIA_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/
-- *** FIDE_PACIENTE_ENFERMEDAD_TB ***
CREATE OR REPLACE TRIGGER FIDE_PACIENTE_ENFERMEDAD_UPDATE_TRG
BEFORE UPDATE ON FIDE_PACIENTE_ENFERMEDAD_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/
-- *** FIDE_FACTURA_TB ***
CREATE OR REPLACE TRIGGER FIDE_FACTURA_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
:NEW.CREADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');--NOMBRE DE QUIEN LO CREO
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.ACCION:='INSERT';
:NEW.ID_FACTURA :=FIDE_FACTURA_ID_COMPUESTO_FN();
END;
/
-- TRIGGER PARA AUDITORIA POR TUPLA UPDATE
CREATE OR REPLACE TRIGGER FIDE_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');--NOMBRE DE QUIEN LO CREO
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;
/
-- *** FIDE_SERVICIO_TB ***
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_SERVICIO_TB FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_SERVICIO := ID_SERVICIO_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');--NOMBRE DE QUIEN LO CREO
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;

-- *** FIDE_CARRITO_TB ***

CREATE OR REPLACE TRIGGER FIDE_CARRITO_SEQ_INSERT_TRG
BEFORE INSERT ON FIDE_CARRITO_TB FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_CARRITO := ID_CARRITO_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CARRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
:NEW.MODIFICADO_POR :=SYS_CONTEXT('USERENV','SESSION_USER');--NOMBRE DE QUIEN LO CREO
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.ACCION:='UPDATE';
END;

--NOTA: HACER SOLO AUDITORIA EN LAS TABLAS INTERMEDIAS (SIN ID)
-------------------------------------------------------------------------------

-------------------------------FIN TRIGGERS------------------------------------

