/* PROYECTO LENGUAJES DE BASE DE DATOS "SALUDTOTAL"          
FECHA DE CREACION: 17/11/25 
DESCRIPCION: CREACION DE LAS VISTAS
*/

CREATE OR REPLACE VIEW FIDE_RESUMEN_VENTAS_SUCURSAL_V AS
SELECT 
    S.NOMBRE AS NOMBRE_SUCURSAL,
    COUNT(F.ID_FACTURA) AS "CANTIDAD FACTURAS",
    SUM(F.SUBTOTAL) AS SUBTOTAL_ACUMULADO,
    SUM(F.IVA) AS IVA_ACUMULADO,
    SUM(F.MONTO_TOTAL) AS TOTAL_GENERAL
FROM FIDE_SUCURSAL_TB S
JOIN FIDE_CITA_TB C ON S.ID_SUCURSAL = C.ID_SUCURSAL
JOIN FIDE_FACTURA_TB F ON C.ID_CITA = F.ID_CITA
WHERE F.ID_ESTADO = 1 -- Solo facturas activas
GROUP BY S.NOMBRE;
----------------
SELECT * FROM FIDE_RESUMEN_VENTAS_SUCURSAL_V;
----------------
/

CREATE OR REPLACE VIEW FIDE_DIRECTORIO_PERSONAL_V AS
SELECT 
    P.ID_PERSONAL,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO AS NOMBRE_COMPLETO,
    R.NOMBRE_ROL AS PUESTO,
    S.NOMBRE AS "SEDE ASIGNADA",
    P.FECHA_CONTRATACION,
    CASE 
        WHEN P.ID_ESTADO = 1 THEN 'Activo'
        ELSE 'Inactivo'
    END AS ESTADO_ACTUAL
FROM FIDE_PERSONAL_TB P
JOIN FIDE_ROL_PERSONAL_TB R ON P.ID_ROL_PERSONAL = R.ID_ROL_PERSONAL
JOIN FIDE_SUCURSAL_TB S ON P.ID_SUCURSAL = S.ID_SUCURSAL;
----------------
SELECT * FROM FIDE_DIRECTORIO_PERSONAL_V;
----------------

CREATE OR REPLACE VIEW FIDE_PACIENTES_CON_ALERGIAS_V
 AS
SELECT
    P.NOMBRE|| ' ' ||APELLIDO_PATERNO|| ' ' ||APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    A.NOMBRE_ALERGIA,
    PA.NOTAS AS NOTA
FROM
    FIDE_PACIENTE_TB P, FIDE_PACIENTE_ALERGIA_TB PA, FIDE_ALERGIA_TB A
WHERE
    P.ID_PACIENTE = PA.ID_PACIENTE
AND 
    PA.ID_ALERGIA =  A.ID_ALERGIA;
/   
----------------
SELECT * FROM FIDE_PACIENTES_CON_ALERGIAS_V;
----------------

--- VER PACIENTES CON ENFERMEDADES ---
CREATE OR REPLACE VIEW FIDE_PACIENTES_CON_ENFERMEDADES_V AS
SELECT
    P.NOMBRE|| ' ' ||APELLIDO_PATERNO|| ' ' ||APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    A.NOMBRE_ENFERMEDAD,
    PA.NOTAS AS NOTA
FROM
    FIDE_PACIENTE_TB P, FIDE_PACIENTE_ENFERMEDAD_TB PA, FIDE_ENFERMEDAD_CRONICA_TB A
WHERE
    P.ID_PACIENTE = PA.ID_PACIENTE
AND 
    PA.ID_ENFERMEDAD =  A.ID_ENFERMEDAD;
/
----------------
SELECT * FROM FIDE_PACIENTES_CON_ENFERMEDADES_V;
----------------

---  PACIENTES CON CITAS ---
CREATE OR REPLACE VIEW FIDE_PACIENTES_CON_CITAS_V AS
SELECT
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    C.FECHA_HORA_CITA,
    PE.NOMBRE || ' ' || PE.APELLIDO_PATERNO || ' ' || PE.APELLIDO_MATERNO AS NOMBRE_MEDICO
FROM
    FIDE_PACIENTE_TB P, FIDE_CITA_TB C, FIDE_PERSONAL_TB PE
WHERE
     C.ID_PACIENTE = P.ID_PACIENTE
AND 
    C.ID_MEDICO = PE.ID_PERSONAL;
/
----------------
SELECT * FROM FIDE_PACIENTES_CON_CITAS_V;

-------------NUEVAS VISTAS

CREATE OR REPLACE VIEW FIDE_FACTURAS_V AS
SELECT 
    F.ID_FACTURA,
    TO_CHAR(F.FECHA_EMISION, 'YYYY-MM-DD HH24:MI') AS FECHA_FORMATO,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO AS NOMBRE_PACIENTE,
    S.NOMBRE AS SUCURSAL,
    F.SUBTOTAL AS SUBTOTAL,
    F.IVA AS IVA,
    F.MONTO_TOTAL,
    E.NOMBRE_ESTADO AS ESTADO
FROM FIDE_FACTURA_TB F
JOIN FIDE_CITA_TB C ON F.ID_CITA = C.ID_CITA
JOIN FIDE_PACIENTE_TB P ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN FIDE_SUCURSAL_TB S ON C.ID_SUCURSAL = S.ID_SUCURSAL
JOIN FIDE_ESTADO_TB E ON F.ID_ESTADO = E.ID_ESTADO;
/
CREATE OR REPLACE VIEW FIDE_INVENTARIO_V AS
SELECT 
        INV.ID_INVENTARIO, 
        INV.STOCK, 
        INV.FECHA_VENCIMIENTO, 
        INV.ID_ESTADO,
        S.NOMBRE AS NOMBRE_SUCURSAL,
        M.NOMBRE_COMERCIAL || ' (' || M.PRESENTACION || ')' AS DETALLE_MEDICAMENTO
FROM FIDE_INVENTARIO_TB INV
INNER JOIN FIDE_SUCURSAL_TB S ON INV.ID_SUCURSAL = S.ID_SUCURSAL
INNER JOIN FIDE_MEDICAMENTO_TB M ON INV.ID_MEDICAMENTO = M.ID_MEDICAMENTO
ORDER BY S.NOMBRE, M.NOMBRE_COMERCIAL
/
CREATE OR REPLACE VIEW FIDE_INVENTARIO_POR_ID_V AS
    SELECT 
        I.ID_INVENTARIO, 
        I.STOCK, 
        I.FECHA_VENCIMIENTO, 
        I.ID_ESTADO,
        I.ID_SUCURSAL,
        I.ID_MEDICAMENTO,
        S.NOMBRE AS NOMBRE_SUCURSAL, -- ¡Nuevo!
        M.NOMBRE_COMERCIAL || ' (' || M.PRESENTACION || ')' AS DETALLE_MEDICAMENTO
    FROM FIDE_INVENTARIO_TB I
    INNER JOIN FIDE_SUCURSAL_TB S ON I.ID_SUCURSAL = S.ID_SUCURSAL
    INNER JOIN FIDE_MEDICAMENTO_TB M ON I.ID_MEDICAMENTO = M.ID_MEDICAMENTO
/

CREATE OR REPLACE VIEW FIDE_MEDICAMENTOS_INFO_V AS
SELECT 
    M.ID_MEDICAMENTO,
    M.NOMBRE_COMERCIAL,
    M.PRINCIPIO_ACTIVO,
    M.PRESENTACION,
    M.PRECIO_VENTA, -- Asegúrate de que esta columna exista, si se llama PRECIO cámbialo
    M.ID_ESTADO,
    --datos de inventario y ucursal
    --uso de NVL para manejo de nulos en caso de que por ejemplo, no hubiera inventario
    NVL(I.STOCK, 0) AS STOCK,
    S.NOMBRE AS NOMBRE_SUCURSAL
FROM FIDE_MEDICAMENTO_TB M
LEFT JOIN FIDE_INVENTARIO_TB I ON M.ID_MEDICAMENTO = I.ID_MEDICAMENTO
LEFT JOIN FIDE_SUCURSAL_TB S ON I.ID_SUCURSAL = S.ID_SUCURSAL;
/
CREATE OR REPLACE VIEW FIDE_PERSONAL_V AS
SELECT 
    P.ID_PERSONAL, 
    P.NOMBRE, 
    P.APELLIDO_PATERNO, 
    P.APELLIDO_MATERNO, 
    P.FECHA_CONTRATACION, 
    P.ID_ESTADO,
    R.NOMBRE_ROL, --traemos el nombre del rol
    S.NOMBRE AS NOMBRE_SUCURSAL --traemos el nombre de la sucursal
FROM FIDE_PERSONAL_TB P
INNER JOIN FIDE_ROL_PERSONAL_TB R ON P.ID_ROL_PERSONAL = R.ID_ROL_PERSONAL
INNER JOIN FIDE_SUCURSAL_TB S ON P.ID_SUCURSAL = S.ID_SUCURSAL
ORDER BY P.ID_PERSONAL ASC
/

CREATE OR REPLACE VIEW FIDE_PACIENTES_V AS
SELECT 
    PA.ID_PACIENTE, 
    PA.NOMBRE, 
    PA.APELLIDO_PATERNO, 
    PA.APELLIDO_MATERNO, 
    PA.FECHA_NACIMIENTO, 
    PA.ID_ESTADO,
    --concatenacion de direccion
    P.NOMBRE_PROVINCIA || ', ' || C.NOMBRE_CANTON || ', ' || D.NOMBRE_DISTRITO || ': ' || DIR.DETALLES AS DIRECCION_COMPLETA,
    DIR.ID_DIRECCION --mantenemos el ID por si se ocupa para editar, pero mostramos el texto
FROM FIDE_PACIENTE_TB PA
INNER JOIN FIDE_DIRECCIONES_TB DIR ON PA.ID_DIRECCION = DIR.ID_DIRECCION
INNER JOIN FIDE_DISTRITOS_TB D ON DIR.ID_DISTRITO = D.ID_DISTRITO
INNER JOIN FIDE_CANTONES_TB C ON D.ID_CANTON = C.ID_CANTON
INNER JOIN FIDE_PROVINCIAS_TB P ON C.ID_PROVINCIA = P.ID_PROVINCIA
ORDER BY PA.ID_PACIENTE ASC
/
CREATE OR REPLACE VIEW FIDE_SUCURSALES_V AS
SELECT 
    S.ID_SUCURSAL, 
    S.NOMBRE, 
    S.TELEFONO, 
    S.ID_ESTADO,
--Concatenamos Provincia, Canton, Distrito y Detalles
    P.NOMBRE_PROVINCIA || ', ' || C.NOMBRE_CANTON || ', ' || D.NOMBRE_DISTRITO || ': ' || DIR.DETALLES AS DIRECCION_COMPLETA
FROM FIDE_SUCURSAL_TB S
INNER JOIN FIDE_DIRECCIONES_TB DIR ON S.ID_DIRECCION = DIR.ID_DIRECCION
INNER JOIN FIDE_DISTRITOS_TB D ON DIR.ID_DISTRITO = D.ID_DISTRITO
INNER JOIN FIDE_CANTONES_TB C ON D.ID_CANTON = C.ID_CANTON
INNER JOIN FIDE_PROVINCIAS_TB P ON C.ID_PROVINCIA = P.ID_PROVINCIA
ORDER BY S.ID_SUCURSAL ASC
/
CREATE OR REPLACE VIEW FIDE_SUCURSALES_OBTENER_FULL_V AS 
SELECT 
    S.ID_SUCURSAL, S.NOMBRE, S.TELEFONO, S.ID_ESTADO,
    DIR.ID_DIRECCION, DIR.DETALLES,
    D.ID_DISTRITO,
    C.ID_CANTON,
    PRO.ID_PROVINCIA
FROM FIDE_SUCURSAL_TB S
INNER JOIN FIDE_DIRECCIONES_TB DIR ON S.ID_DIRECCION = DIR.ID_DIRECCION
INNER JOIN FIDE_DISTRITOS_TB D ON DIR.ID_DISTRITO = D.ID_DISTRITO
INNER JOIN FIDE_CANTONES_TB C ON D.ID_CANTON = C.ID_CANTON
INNER JOIN FIDE_PROVINCIAS_TB PRO ON C.ID_PROVINCIA = PRO.ID_PROVINCIA;
